# ubios/makefile.mac 8/8/2011 dwg - 

DELIM   = /
SPREFIX = /Developer/sdcc
SDAS    = $(SPREFIX)/bin/sdasz80
SDASFLG = -plosff -Iinc
SDCC    = $(SPREFIX)/bin/sdcc
SDCCFLG = -c -mz80 -D__SDCC__=1 -I inc
SDCCLIB = $(SPREFIX)/share/sdcc/lib/z80
SDLD    = $(SPREFIX)/bin/sdldz80
SDLDFLG =  
TPREFIX = 
TCC     = gcc
TCCFLG  = -I inc
COPY    = cp
DEL     = rm
DELFLG  = -f 
# use native ECHO o Mac OS X
ECHO    = echo 
REN     = mv
EXE     = 

include common.mak



