;
;==================================================================================================
;   WRAPPER FOR ZSDOS/ZDDOS FOR N8VEM PROJECT
;   WAYNE WARTHEN - 2011-01-09
;==================================================================================================
;
; THE FOLLOWING MACROS DO THE HEAVY LIFTING TO MAKE THE ZSDOS SOURCE
; COMPATIBLE WITH TASM
;
#DEFINE	EQU	.EQU
#DEFINE	NAME	\;
#DEFINE	PAGE	.PAGE
#DEFINE	CSEG	.CSEG
#DEFINE	DSEG	.DSEG
#DEFINE	ORG	.ORG
#DEFINE	END	.END
#DEFINE	IF	.IF
#DEFINE	ELSE	.ELSE
#DEFINE	ENDIF	.ENDIF
#DEFINE	DEFB	.DB
#DEFINE	DEFW	.DW
#DEFINE	FILL	.FILL
;
; ZSDOS USES A .LIB FILE FOR CONFIGURATION.  SINCE TASM HAS NO SUPPORT FOR THIS
; WE JUST INCLUDE THE FILE HERE.
;
#DEFINE	BLD_ZSDOS11	TRUE	; TRUE BUILDS VER 1.1, FALSE BUILDS VER 1.2
#DEFINE	BLD_ZS		TRUE	; TRUE FOR ZSDOS BUILD, FALSE FOR ZDDOS BUILD
#DEFINE	BLD_ROM		FALSE
#INCLUDE "zsdos.lib"
;
;
; ESTABLISH STARTING ADDRESS FOR ZSDOS
;
	.ORG	0D800H
;
; NOW INCLUDE THE MAIN SOURCE
;
#INCLUDE "zsdos-gp.z80"