;
;==================================================================================================
;   HDSK DISK DRIVER - DATA
;==================================================================================================
;
HDSK_SLICETRKS	.EQU	65			; TRACKS PER SLICE
HDSK_TRKSIZE	.EQU	128			; SIZE OF TRACK (IN KB)
HDSK_SLICESIZE	.EQU	((HDSK_SLICETRKS * HDSK_TRKSIZE) + 1023) / 1024 ; SIZE OF EACH SLICE (IN MB)
HDSK_NUMSLICES	.EQU	HDSKCAPACITY / HDSK_SLICESIZE ; TOTAL SLICES IN DEVICE
HDSK0_SLICEDEF	.EQU	0			; DEFAULT SLICE FOR UNIT 0
HDSK1_SLICEDEF	.EQU	1			; DEFAULT SLICE FOR UNIT 1
HDSK2_SLICEDEF	.EQU	2			; DEFAULT SLICE FOR UNIT 0
HDSK3_SLICEDEF	.EQU	3			; DEFAULT SLICE FOR UNIT 1
;
		.DB	DIODEV_HDSK + 0
HDSKDPH0 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	HDSKCSV0,HDSKALV0
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
HDSK0_SLICE	.DW	HDSK0_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	HDSK_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
		.DB	DIODEV_HDSK + 0
HDSKDPH1 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	HDSKCSV1,HDSKALV1
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
HDSK1_SLICE	.DW	HDSK1_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	HDSK_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
		.DB	DIODEV_HDSK + 0
HDSKDPH2 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	HDSKCSV2,HDSKALV2
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
HDSK2_SLICE	.DW	HDSK2_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	HDSK_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
		.DB	DIODEV_HDSK + 0
HDSKDPH3 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	HDSKCSV3,HDSKALV3
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
HDSK3_SLICE	.DW	HDSK3_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	HDSK_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
HDSKCKS		.EQU	0			; CKS: 0 FOR NON-REMOVABLE MEDIA
HDSKALS		.EQU	256			; ALS: BLKS / 8 = 2048 / 8 = 256 (ROUNDED UP)
;
HDSKCSV0:	.FILL	HDSKCKS			; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
HDSKALV0:	.FILL	HDSKALS			; MAX OF 2048 DATA BLOCKS
HDSKCSV1:	.FILL	HDSKCKS			; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
HDSKALV1:	.FILL	HDSKALS			; MAX OF 2048 DATA BLOCKS
HDSKCSV2:	.FILL	HDSKCKS			; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
HDSKALV2:	.FILL	HDSKALS			; MAX OF 2048 DATA BLOCKS
HDSKCSV3:	.FILL	HDSKCKS			; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
HDSKALV3:	.FILL	HDSKALS			; MAX OF 2048 DATA BLOCKS
