;
;==================================================================================================
;   PPPSD DISK DRIVER - DATA
;==================================================================================================
;
PPPSD_SLICETRKS	.EQU	65			; TRACKS PER SLICE
PPPSD_TRKSIZE	.EQU	128			; SIZE OF TRACK (IN KB)
PPPSD_SLICESIZE	.EQU	((PPPSD_SLICETRKS * PPPSD_TRKSIZE) + 1023) / 1024 ; SIZE OF EACH SLICE (IN MB)
PPPSD_NUMSLICES	.EQU	PPPSDCAPACITY / PPPSD_SLICESIZE	 ; TOTAL SLICES IN DEVICE
PPPSD0_SLICEDEF	.EQU	0			; DEFAULT SLICE FOR UNIT 0
PPPSD1_SLICEDEF	.EQU	1			; DEFAULT SLICE FOR UNIT 1
PPPSD2_SLICEDEF	.EQU	2			; DEFAULT SLICE FOR UNIT 0
PPPSD3_SLICEDEF	.EQU	3			; DEFAULT SLICE FOR UNIT 1
;
		.DB	DIODEV_PPPSD + 0
PPPSDDPH0 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	PPPSDCSV0,PPPSDALV0
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
PPPSD0_SLICE	.DW	PPPSD0_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	PPPSD_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
		.DB	DIODEV_PPPSD + 0
PPPSDDPH1 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	PPPSDCSV1,PPPSDALV1
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
PPPSD1_SLICE	.DW	PPPSD1_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	PPPSD_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
		.DB	DIODEV_PPPSD + 0
PPPSDDPH2 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	PPPSDCSV2,PPPSDALV2
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
PPPSD2_SLICE	.DW	PPPSD2_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	PPPSD_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
		.DB	DIODEV_PPPSD + 0
PPPSDDPH3 	.DW 	0000,0000
		.DW 	0000,0000
		.DW 	DIRBF,DPB_HD
		.DW 	PPPSDCSV3,PPPSDALV3
		.DB	"LU"			; LOGICAL UNIT ENHANCEMENT SIGNATURE
PPPSD3_SLICE	.DW	PPPSD3_SLICEDEF		; CURRENTLY ACTIVE SLICE
		.DW	PPPSD_NUMSLICES		; NUMBER OF SLICES AVAILABLE
;
PPPSDCKS	.EQU	0			; CKS: 0 FOR NON-REMOVABLE MEDIA
PPPSDALS	.EQU	256			; ALS: BLKS / 8 = 2048 / 8 = 256 (ROUNDED UP)
;
PPPSDCSV0	.FILL	PPPSDCKS		; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
PPPSDALV0	.FILL	PPPSDALS		; MAX OF 2048 DATA BLOCKS
PPPSDCSV1	.FILL	PPPSDCKS		; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
PPPSDALV1	.FILL	PPPSDALS		; MAX OF 2048 DATA BLOCKS
PPPSDCSV2	.FILL	PPPSDCKS		; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
PPPSDALV2	.FILL	PPPSDALS		; MAX OF 2048 DATA BLOCKS
PPPSDCSV3	.FILL	PPPSDCKS		; NO DIRECTORY CHECKSUM, NON-REMOVABLE DRIVE
PPPSDALV3	.FILL	PPPSDALS		; MAX OF 2048 DATA BLOCKS
