;
;==================================================================================================
;   MARK IV STANDARD CONFIGURATION
;==================================================================================================
;
#include "cfg_mk4.asm"
;
Z180_CLKDIV	.SET	1		; 0=OSC/2, 1=OSC, 2=OSC*2
Z180_MEMWAIT	.SET	0		; MEMORY WAIT STATES (0-3)
Z180_IOWAIT	.SET	1		; ADD (0-3) I/O WAIT STATES ABOVE 1 W/S BUILT-IN
;
FDENABLE	.SET	FALSE		; TRUE FOR FLOPPY DEVICE SUPPORT
FDMODE		.SET	FDMODE_DIDE	; FDMODE_DIO, FDMODE_DIDE, FDMODE_DIO3
;
IDEENABLE	.SET	TRUE		; TRUE FOR IDE DEVICE SUPPORT
IDEMODE		.SET	IDEMODE_MK4	; IDEMODE_MK4, IDEMODE_DIO, IDEMODE_DIDE
;
PPIDEENABLE	.SET	FALSE		; TRUE FOR PPIDE DEVICE SUPPORT
PPIDEMODE	.SET	PPIDEMODE_MFP	; PPIDEMODE_MFP, PPPIDEMODE_DIO3
;
SDENABLE	.SET	TRUE		; TRUE FOR SD DEVICE SUPPORT
SDMODE		.SET	SDMODE_MK4	; SDMODE_MK4, SDMODE_DSD
;
PRPENABLE	.SET	TRUE		; TRUE FOR PROPIO BOARD SUPPORT (VIDEO, KBD, & SD CARD)
;
VGAENABLE	.SET	TRUE		; TRUE FOR VGA BOARD VIDEO & KBD SUPPORT
CVDUENABLE	.SET	TRUE		; TRUE FOR CVDU BOARD VIDEO & KBD SUPPORT
VDUENABLE	.SET	FALSE		; TRUE FOR VDU BOARD VIDEO & KBD SUPPORT
;
CRTACT		.SET	FALSE		; TRUE TO ACTIVATE CRT AT STARTUP (BOOT ON CRT)
