;
;==================================================================================================
;   SBC DISKIO V3 + CVDU CONFIGURATION
;==================================================================================================
;
CRTACT		.SET	FALSE		; ACTIVATE CRT AT STARTUP
VDAEMU		.SET	EMUTYP_ANSI	; SELECT ANSI TERMINAL EMULATION
;
CVDUENABLE	.SET	TRUE		; ENABLE CVDU BOARD SUPPORT
;
KBDENABLE	.SET	TRUE		; PS/2 KEYBOARD ON I8242
;
TTYENABLE	.SET	TRUE		; INCLUDE TTY EMULATION SUPPORT
ANSIENABLE	.SET	TRUE		; INCLUDE ANSI EMULATION SUPPORT
;
FDENABLE	.SET	TRUE		; ENABLE FLOPPY SUPPORT
FDMODE		.SET	FDMODE_DIO3	; USE DISKIO V3 MODE
;
PPIDEENABLE	.SET	TRUE		; ENABLE PPIDE SUPPORT
PPIDEMODE	.SET	PPIDEMODE_DIO3	; PPIDEMODE_SBC, PPPIDEMODE_DIO3, PPIDEMODE_MFP, PPIDEMODE_N8
