
; Batch File:  NZSUB.SUB
; Author:      Joe Wright
; Date:        8 November 1988

; This file demonstrates NZSUB's ability to handle 'formatted'
; input files.  The programmer will note the similarity to
; annotated assembly source files.

; This file will also serve as the documentation of NZSUB's
; features and function.

; As these lines suggest, any line that begins with a ; is considered
; a full-line comment and is ignored.

û         Thå  lefô squigglù brackeô '{§ aó  thå  firsô 
          characteò  oæ  á  linå  wilì  puô  NZSUÂ   iî 
          'comment§  mode®  Alì  subsequenô  characteró 
          untiì  á  righô  squigglù  brackeô  wilì   bå 
          ignored®  Checë thió out®  }

; The ; character is usually the command separator for a Z3
; multiple command line.  It is therefore a 'normal' character
; unless it is the first one and may appear freely in the command
; line preceded by anything except a space.

; Blank lines are ignored in any case.  

{
Alì oæ thå abovå lineó anä theså lineó arå someho÷ commenteä  ouô 
oò  arå blanë anä thereforå wilì noô appeaò iî thå  $$$.SUÂ  filå 
whicè wilì bå thå resulô oæ alì this®  

NZSUÂ  ió  completelù CP/Í compatible®  Nonetheless¬  iæ  runninç 
undeò  Ú-System¬  DUº anä DIRº formó maù bå useä tï  declarå  thå 
sourcå file®  Thå sourcå filå ió assumeä tï havå typå .SUÂ unlesó 
otherwiså declared®  Iî anù case¬ $$$.SUÂ wilì bå writteî tï  thå 
currenô directory®  
}

» Ok¬ dowî tï business.  The main point of all this is to relax
; some of the constraints on command line formatting so that
; a batch file becomes more legible and therefore maintainable.

; Command lines may be indented with any combination of spaces
; and tabs.  A tab within a command line will be converted to
; a space.  Spaces between the last command character and the
; in-line comment ';' or ';;' will be removed and the comment
; ignored.  The ';;' ZEX form may be used but is unnecessary
; if the ';' is preceded by at least one space (or tab).

;;
;; NZSUB Demo Program
;;
	$; nzsub demonstration	;; Use $; for literal ;
	DIR	*.COM		;; Let's see what we've got

	echo	display source files? (yes or no)

	 IF INPUT		; Ask the user (indented)
	DIR	*.Z80
	 FI			; endif
;;
;; End of NZSUB Demo Program
;
; End of NZSUB.SUB
