1                    Turbo Pascal general installation System
2                  Choose installation item from the following:
3
4                         Screen installation   |   Quit
5
6                                 Enter S or Q:
13  ->
101 Nothing
 ^Q: Quit, ^R: Last page, ^C: Next page, <RETURN>: Select terminal:
 Wait Sorting Definitions
 Change to:
 (Y/N)? 
 y
 n
 Text file name:
 Command:
 Numeric entry expected
 Legal range is 
 , please re-enter: 
 Choose one of the following terminals:
 None of the above   ( Max. 20 Characters )
 Delete a definition ( Max. 20 Characters )
 Which terminal? (Enter no. or ^Q to exit): 
 Delete terminal? (Enter no. or ^Q to exit):
 Do you want to modify this definition before installation? 
 Terminal type:
 Send an initialization string to the terminal?
 Initializaion defined as a command string? (No = a file)
 Send a reset string to the terminal
 Reset defined as a command? (No = a file)
 CURSOR LEAD-IN command: 
 CURSOR POSITIONING COMMAND to send between line and column:   
 CURSOR POSITIONING COMMAND to send after both line and column:
 Column first
 OFFSET to add to LINE:  
 OFFSET to add to COLUMN:
 Binary address
 Number of ASCII digits (2 or 3): 
 CLEAR SCREEN command: 
 Does CLEAR SCREEN also HOME cursor
 HOME command: 
 DELETE LINE command: 
 INSERT LINE command: 
 ERASE TO END OF LINE command:
 START HIGHLIGHTING command:  
 END HIGHLIGHTING command:    
 Number of rows (lines) on your screen: 
 Number of columns on your screen:      
 Delay after CURSOR ADDRESS (0-255 ms):                     
 Delay after CLEAR, DELETE and INSERT (0-255 ms):           
 Delay after ERASE TO END OF LINE and HIGHLIGHT (0-255 ms): 
 Is this definition correct?
                     Hardware dependent information
 Operating frequency of your microprocessor in MHz (for delays):
101 Nothing
200 Choose one of the following displays:
201 Which display? (Enter no. or Q to exit):
202 Default display mode
203 Monochrome display
204 Color display 80x25
205 Color display 40x25
206 b/w   display 80x25
207 b/w   display 40x25
