# makefile 6/13/2012 dwg - build Apps using Aztec C Cross Compiler for Z80

MODE    = debug
#MODE    = release

CC      = bin\ccz -D$(MODE) 
FLAGS   = -o $@
AS      = bin\as80
LN      = bin\ln80
LNFLAGS = -o $@

CHARS   = $(MODE)\chars.o
CPMNAME = $(MODE)\cpmname.o $(MODE)\cnamept1.o $(MODE)\cnamept2.o $(MODE)\cnamept3.o $(MODE)\cnamept4.o
LABEL   = $(MODE)\label.o
MAP     = $(MODE)\map.o
META    = $(MODE)\meta.o 
SYSGEN  = $(MODE)\sysgen.o 
TESTER  = $(MODE)\tester.o
VIEW	= $(MODE)\view.o
GENOBJS = $(MODE)\asmiface.o $(MODE)\cbanner.o $(MODE)\bdoscall.o $(MODE)\bioscall.o $(MODE)\clogical.o $(MODE)\cmemory.o $(MODE)\diagnose.o $(MODE)\sectorio.o $(MODE)\ctermcap.o c.lib

.c.o:
	$(CC) $(FLAGS) $<

.asm.o:
	$(AS) $(FLAGS) $<

all:	$(MODE)\tester.com $(MODE)\cpmname.com  $(MODE)\chars.com \
	$(MODE)\sysgen.com $(MODE)\label.com    $(MODE)\map.com   \
	$(MODE)\meta.com   $(MODE)\view.com

$(MODE)\chars.com:	$(CHARS) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(CHARS) $(GENOBJS)
!

$(MODE)\cpmname.com:	$(CPMNAME) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(CPMNAME) $(GENOBJS)
!

$(MODE)\sysgen.com:	$(SYSGEN) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(SYSGEN) $(GENOBJS)
!
	
$(MODE)\label.com:	$(LABEL) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(LABEL) $(GENOBJS)
!

$(MODE)\map.com:	$(MAP) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(MAP) $(GENOBJS)
!

$(MODE)\meta.com:	$(META) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(META) $(GENOBJS)
!

$(MODE)\tester.com:	$(TESTER) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(TESTER) $(GENOBJS)
!

$(MODE)\view.com:	$(VIEW) $(GENOBJS)
	$(LN) $(LNFLAGS) -F &&!
$(VIEW) $(GENOBJS)
!

$(MODE)\asmiface.o:	asmiface.asm

$(MODE)\cbanner.o:	cbanner.c

$(MODE)\chars.o:	chars.c

$(MODE)\clogical.o:	clogical.c
	
$(MODE)\cmemory.o:	cmemory.c

$(MODE)\cpmname.o:	cpmname.c

$(MODE)\cnamept1.o:	cnamept1.c

$(MODE)\cnamept2.o:	cnamept2.c

$(MODE)\cnamept3.o:	cnamept3.c

$(MODE)\cnamept4.o:	cnamept4.c

$(MODE)\ctermcap.o:	ctermcap.c

$(MODE)\bdoscall.o:	bdoscall.asm

$(MODE)\bioscall.o:	bioscall.asm

$(MODE)\diagnose.o:	diagnose.asm

$(MODE)\label.o:	label.c

$(MODE)\map.o:		map.c

$(MODE)\meta.o:		meta.c

$(MODE)\sectorio.o:	sectorio.c
	
$(MODE)\sysgen.o:	sysgen.c

$(MODE)\tester.o:	tester.c

$(MODE)\view.o:		view.c

clean:
	if exist cpmname.com erase cpmname.com
	if exist *.bak erase *.bak
	if exist *.o erase *.o
	if exist debug\*.*   erase debug\*.*
	if exist release\*.* erase release\*.*
