
DELIM   = \
SDRIVE  = C:
SPREFIX = $(SDRIVE)\sdcc
SDAS    = $(SPREFIX)\bin\sdasz80
SDASFLG = -plosff
SDCC    = $(SPREFIX)\bin\sdcc
SDCCFLG = -c -mz80 -D__SDCC__=1 -I inc
SDCCLIB = $(SPREFIX)\lib\z80
SDLD    = $(SPREFIX)\bin\sdldz80
SDLDFLG =  
TPREFIX =
TCC     = gcc
TCCOPT  = -I inc
COPY    = copy
DEL     = erase
DELFLG  = /Q 
REN     = rename
ECHO    = $(BIN)lecholf
EXE     = .exe

.include common.mak


