@echo off
setlocal

where git >nul 2>nul
if errorlevel 1 goto nogit
git diff --quiet
if errorlevel 1 goto dirty
git diff --cached --quiet
if errorlevel 1 goto dirty
for /f %%i in ('git rev-parse --short HEAD') do set BUILDID=%%i
goto gen

:nogit
echo Build.cmd: WARNING -- git not found on PATH, BUILDID will be "unknown"
set BUILDID=unknown
goto gen

:dirty
echo Build.cmd: working tree is dirty -- commit before building
exit /b 1

:gen
echo /* GENERATED BY Build.cmd -- DO NOT EDIT BY HAND */ > buildid.h
echo #define BUILDID "%BUILDID%" >> buildid.h

set TOOLS=../../../../Tools
set PATH=%TOOLS%\zxcc;%PATH%

set HITECHDIR=../../../Images/d_hitechc/u0/
set BINDIR80=%HITECHDIR%
set LIBDIR80=%HITECHDIR%
set INCDIR80=%HITECHDIR%

zxcc C --C --N bfi2c.c || exit /b
zxcc C --C --N tick.c || exit /b
zxcc C --C --N i2clcd.c || exit /b
zxcc C --C --N vk16text.c || exit /b
zxcc C --C --N rtcds7.c || exit /b
zxcc C --C --N ledsw.c || exit /b

zxcc LIBR -r -common.lib -bfi2c.obj || exit /b
zxcc LIBR -r -common.lib -tick.obj || exit /b

zxcc C --V --N i2clcd.obj common.lib || exit /b
zxcc C --V --N vk16text.obj common.lib || exit /b
zxcc C --V --N rtcds7.obj bfi2c.obj || exit /b
zxcc C --V --N ledsw.obj bfi2c.obj || exit /b

copy /Y i2clcd.com ..\..\..\..\Binary\Apps\Test\ || exit /b
copy /Y vk16text.com ..\..\..\..\Binary\Apps\Test\ || exit /b
copy /Y rtcds7.com ..\..\..\..\Binary\Apps\Test\ || exit /b
copy /Y ledsw.com ..\..\..\..\Binary\Apps\Test\ || exit /b
