#!/bin/bash
# Regenerates buildid.h with the current git commit id. Refuses on a
# dirty tree, no "-dirty" fallback.
set -euo pipefail

DIR="$(dirname "$(readlink -f "$0")")"
cd "$DIR"

if ! git diff --quiet || ! git diff --cached --quiet; then
	echo "gen-buildid.sh: working tree is dirty -- commit before building" >&2
	git status --short >&2
	exit 1
fi

HASH="$(git rev-parse --short HEAD)"

cat > buildid.h <<EOF
/* GENERATED BY gen-buildid.sh -- DO NOT EDIT BY HAND */
#define BUILDID "$HASH"
EOF
