#!/bin/bash
# Regenerates buildid.h with the current git commit id. Falls back to
# "Source" when git isn't installed or this isn't a git checkout.
# A dirty tree appends a single "+" marker.

set -euo pipefail

DIR="$(dirname "$(readlink -f "$0")")"
cd "$DIR"

HASH="Source"

if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
	HASH="$(git rev-parse --short HEAD)"
	if ! git diff --quiet || ! git diff --cached --quiet; then
		HASH="${HASH}+"
	fi
else
	echo "gen-buildid.sh: WARNING: not a git checkout, BUILDID will be \"Source\"" >&2
fi

cat > buildid.h <<EOF
/* GENERATED BY gen-buildid.sh -- DO NOT EDIT BY HAND */
#define BUILDID "$HASH"
EOF
