OBJECTS = 
SUBDIRS = DMAmon I2C inttest ppidetst ramtest tstdskng rzsz vdctest kbdtest ps2info 2piotst piomon banktest portswp
DEST = ../../../Binary/Apps/Test
TOOLS =../../../Tools

include $(TOOLS)/Makefile.inc