;
; I2C BUS SCANNER -- PCF8584 ON THE ECB BOARD (SEE i2cscan.asm)
;
PCFECB		.EQU	1
PCFDUO		.EQU	0
PCFPYCIO	.EQU	0
P8X180		.EQU	0
SC126		.EQU	0
SC137		.EQU	0
;
; MATCH WHATEVER THE ACTUAL ROM ON THIS BUS WAS BUILT WITH, SEE
; i2cscan.asm's OWN COMMENTS ON WHY THIS MUST MATCH, NOT JUST DEFAULT ON.
I2CPCF_MULTIMASTER	.EQU	0	; UNKNOWN ROM CONFIG, SAFEST DEFAULT
;
#include "i2cscan.asm"
