OBJECTS = i2cscecb.com i2cscduo.com i2cscpyc.com i2cscp8x.com i2csc126.com i2csc137.com pcfstat.com rtcds7.com i2clcd.com srom.com
DEST = ../../../../Binary/Apps/Test/
TOOLS = ../../../../Tools

USETASM=1
TASMFLAGS=-dWBW

include $(TOOLS)/Makefile.inc
