;
	.ECHO	"pcfstat\n"
;
; PCF8584 STATUS REGISTER (S1) DIAGNOSTIC
; READS S1 AND DECODES ALL 8 BITS PER THE REAL PCF8584 DATASHEET, SECTION
; 6.8.2 (PIN, INIT, STS, BER, AD0/LRB, AAS, LAB, BB). WITH A COMMAND LINE
; ARGUMENT STARTING "R" (E.G. "PCFSTAT R"),
; FIRST WRITES PIN=1 (80H) TO S1, THE DATASHEET'S DOCUMENTED SOFTWARE
; RESET, THEN READS AGAIN SO BOTH STATES SHOW IN ONE RUN.
;
; ANY OTHER ARGUMENT IS TAKEN AS A 2-DIGIT HEX BYTE (E.G. "PCFSTAT 81") AND
; WRITTEN TO S1 DIRECTLY INSTEAD, THEN RE-READ, TO LET YOU PROBE ANY WRITE,
; NOT JUST THE DOCUMENTED PIN=1 RESET (E.G. 81H = PIN=1 *AND* BB=1/FREE,
; WITHOUT RELYING ON THE RESET TO CLEAR BB ITSELF).
;
I2CPCF_BASE	.EQU	40H
I2CPCF_RS0	.EQU	I2CPCF_BASE
I2CPCF_RS1	.EQU	I2CPCF_BASE+1
;
I2CPCF_PIN	.EQU	10000000B
;
	.ORG	100H
;
	LD	SP,STACK
;
	LD	HL,SIGNON
	CALL	_STROUT
;
	CALL	SHOWSTAT
;
	LD	A,(0080H)		; COMMAND TAIL LENGTH
	OR	A
	JP	Z,DONE			; NO ARGUMENT, READ ONLY
	LD	A,(0082H)		; FIRST CHARACTER AFTER THE SEPARATOR
	AND	11011111B		; FORCE UPPERCASE
	CP	'R'
	JP	NZ,TRYHEX
;
	LD	HL,RESETMSG
	CALL	_STROUT
	LD	A,I2CPCF_PIN
	OUT	(I2CPCF_RS1),A
	CALL	SHOWSTAT
	JP	DONE
;
; ANY OTHER ARGUMENT: PARSE AS A 2-DIGIT HEX BYTE AND WRITE IT TO S1 DIRECTLY.
;
TRYHEX:
	LD	A,(0082H)
	CALL	HEXNIB
	JP	C,BADHEX
	RLCA
	RLCA
	RLCA
	RLCA				; NIBBLE INTO THE HIGH 4 BITS
	LD	B,A
	LD	A,(0083H)
	CALL	HEXNIB
	JP	C,BADHEX
	OR	B			; COMBINE HIGH+LOW NIBBLES
	LD	(WRITEVAL),A
	LD	HL,WRITEMSG1
	CALL	_STROUT
	LD	A,(WRITEVAL)
	LD	C,A
	CALL	_HEXOUT
	LD	HL,WRITEMSG2
	CALL	_STROUT
	LD	A,(WRITEVAL)
	OUT	(I2CPCF_RS1),A
	CALL	SHOWSTAT
	JP	DONE
;
BADHEX:
	LD	HL,BADHEXMSG
	CALL	_STROUT
;
DONE:
	JP	0
;
; CONVERT ONE ASCII HEX DIGIT IN A TO A NIBBLE (0-15) IN A.
; RETURNS NC/A=NIBBLE IF VALID, C IF NOT A HEX DIGIT.
;
HEXNIB:
	CP	'0'
	JP	C,HEXNIB_BAD
	CP	'9'+1
	JP	NC,HEXNIB_ALPHA
	SUB	'0'
	OR	A
	RET
HEXNIB_ALPHA:
	AND	11011111B		; FORCE UPPERCASE -- LETTERS ONLY, DIGITS ALREADY
					; HANDLED ABOVE. APPLYING THIS TO A DIGIT CORRUPTS
					; IT (E.G. '8'=38H BECOMES 18H, FAILS THE RANGE
					; CHECK) -- MUST NOT BE DONE UNCONDITIONALLY.
	CP	'A'
	JP	C,HEXNIB_BAD
	CP	'F'+1
	JP	NC,HEXNIB_BAD
	SUB	'A'-10
	OR	A
	RET
HEXNIB_BAD:
	SCF
	RET
;
; READ S1, PRINT THE RAW BYTE, THEN EACH BIT'S MEANING
;
SHOWSTAT:
	IN	A,(I2CPCF_RS1)
	LD	(REGVAL),A
	LD	HL,S1MSG
	CALL	_STROUT
	LD	A,(REGVAL)		; _STROUT CLOBBERS A (LEAVES '$'=24H BEHIND ON RETURN),
	LD	C,A			; MUST RELOAD THE REAL CAPTURED VALUE BEFORE HEX-PRINTING IT
	CALL	_HEXOUT
	CALL	_EOLOUT
;
	LD	A,(REGVAL)
	LD	HL,PINMSG0
	BIT	7,A
	JP	Z,SP1
	LD	HL,PINMSG1
SP1:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,INITMSG0
	BIT	6,A
	JP	Z,SP1B
	LD	HL,INITMSG1
SP1B:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,STSMSG0
	BIT	5,A
	JP	Z,SP1C
	LD	HL,STSMSG1
SP1C:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,BERMSG0
	BIT	4,A
	JP	Z,SP2
	LD	HL,BERMSG1
SP2:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,AD0MSG0
	BIT	3,A
	JP	Z,SP2B
	LD	HL,AD0MSG1
SP2B:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,AASMSG0
	BIT	2,A
	JP	Z,SP3
	LD	HL,AASMSG1
SP3:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,LABMSG0
	BIT	1,A
	JP	Z,SP4
	LD	HL,LABMSG1
SP4:	CALL	_STROUT
;
	LD	A,(REGVAL)
	LD	HL,BBMSG0
	BIT	0,A
	JP	Z,SP5
	LD	HL,BBMSG1
SP5:	CALL	_STROUT
	RET
;
SIGNON:		.DB	"PCFSTAT, PCF8584 STATUS REGISTER (S1)\r\n$"
RESETMSG:	.DB	"\r\nWRITING PIN=1 (80H) SOFTWARE RESET, RE-READING.\r\n$"
WRITEMSG1:	.DB	"\r\nWRITING $"
WRITEMSG2:	.DB	"H TO S1, RE-READING.\r\n$"
BADHEXMSG:	.DB	"\r\nINVALID ARGUMENT -- USE R, OR A 2-DIGIT HEX BYTE (E.G. 81).\r\n$"
S1MSG:		.DB	"S1 = $"
PINMSG0:	.DB	"  PIN=0  ACTIVE, PENDING SERVICE. HOLDS SCL LOW IF IN RECEIVER MODE.\r\n$"
PINMSG1:	.DB	"  PIN=1  INACTIVE, IDLE.\r\n$"
INITMSG0:	.DB	"  INIT=0 INITIALIZED (S2 CLOCK REGISTER HAS BEEN LOADED).\r\n$"
INITMSG1:	.DB	"  INIT=1 NOT YET INITIALIZED (LOGIC 1 UNTIL S2 IS LOADED).\r\n$"
STSMSG0:	.DB	"  STS=0  NO EXTERNAL STOP DETECTED (SLAVE RECEIVER MODE ONLY).\r\n$"
STSMSG1:	.DB	"  STS=1  EXTERNAL STOP CONDITION DETECTED (SLAVE RECEIVER MODE ONLY).\r\n$"
BERMSG0:	.DB	"  BER=0  NO BUS ERROR FLAGGED.\r\n$"
BERMSG1:	.DB	"  BER=1  BUS ERROR DETECTED.\r\n$"
AD0MSG0:	.DB	"  AD0/LRB=0  VALID ONLY WHILE PIN=0. IF AAS=1: OWN ADDRESS (NOT\r\n           GENERAL CALL). IF AAS=0: LAST RECEIVED BIT WAS 0.\r\n$"
AD0MSG1:	.DB	"  AD0/LRB=1  VALID ONLY WHILE PIN=0. IF AAS=1: GENERAL CALL (00H)\r\n           ADDRESSED. IF AAS=0: LAST RECEIVED BIT WAS 1.\r\n$"
AASMSG0:	.DB	"  AAS=0  NOT ADDRESSED AS SLAVE.\r\n$"
AASMSG1:	.DB	"  AAS=1  ADDRESSED AS SLAVE. VALID SINCE PIN=0.\r\n$"
LABMSG0:	.DB	"  LAB=0  NO ARBITRATION LOST.\r\n$"
LABMSG1:	.DB	"  LAB=1  LOST ARBITRATION TO ANOTHER MASTER.\r\n$"
BBMSG0:		.DB	"  BB=0   BUS BUSY.\r\n$"
BBMSG1:		.DB	"  BB=1   BUS FREE.\r\n$"
;
_STROUT:
ST1:	LD	A,(HL)
	CP	'$'
	RET	Z
	LD	C,A
	CALL	_COUT
	INC	HL
	JP	ST1
;
_HEXOUT:
	LD	A,C
	SRL	A
	SRL	A
	SRL	A
	SRL	A
	ADD	A,30H
	CP	3AH
	JP	C,H1
	ADD	A,7
H1:	LD	H,A
	LD	A,C
	AND	0FH
	ADD	A,30H
	CP	3AH
	JP	C,H2
	ADD	A,7
H2:	LD	L,A
	LD	C,H
	CALL	_COUT
	LD	C,L
	CALL	_COUT
	RET
;
_EOLOUT:
	LD	C,13
	CALL	_COUT
	LD	C,10
	CALL	_COUT
	RET
;
_COUT:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	E,C
	LD	C,02H
	CALL	5
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET
;
REGVAL:		.DB	0
WRITEVAL:	.DB	0
;
	.FILL	128
STACK:
	.END
