e:rmac access
e:rmac banner
e:rmac findfile
e:rmac hbios
e:rmac identity
e:rmac labelib
e:rmac memory
e:rmac metadata
e:rmac printers
e:rmac rem
e:rmac setlabel
e:rmac terminal
as asmiface
as bdoscall
as bioscall
cc cbanner
as cbanner
cc clogical
as clogical
cc cmemory
as cmemory
cc cnamept1
as cnamept1
cc cnamept2
as cnamept2
cc cnamept3
as cnamept3
cc cnamept4
as cnamept4
cc cpmname
as cpmname
cc ctermcap
as ctermcap
as diagnose
cc map
as map
cc meta
as meta
cc multifmt
as multifmt
cc sectorio
as sectorio
cc sysgen
as sysgen
cc termtype
as termtype
cc view
as view
e:link access,memory,banner,printers
ln cpmname.o ctermcap.o cnamept1.o cnamept2.o cnamept3.o cnamept4.o cmemory.o diagnose.o bioscall.o bdoscall.o c.lib
e:link findfile,hbios,identity,banner,memory,printers,terminal
ln map.o asmiface.o bioscall.o bdoscall.o clogical.o diagnose.o ctermcap.o c.lib
ln meta.o asmiface.o bioscall.o bdoscall.o cbanner.o clogical.o diagnose.o ctermcap.o sectorio.o c.lib
ln multifmt.o asmiface.o bioscall.o bdoscall.o clogical.o cmemory.o sectorio.o diagnose.o ctermcap.o c.lib
e:link rem
e:link setlabel,labelib,identity,printers,banner,metadata,memory
ln sysgen.o sectorio.o ctermcap.o diagnose.o bdoscall.o bioscall.o c.lib
ln termtype.o asmiface.o ctermcap.o diagnose.o c.lib
ln view.o ctermcap.o diagnose.o bdoscall.o bioscall.o c.lib
e:access access.com
e:access cpmname.com
e:access findfile.com
e:access map.com
e:access meta.com
e:access multifmt.com
e:access rem.com
e:access setlabel.com
e:access sysgen.com
e:access termtype.com
e:access view.com
