/****************************************************************/
/* globals.h 3/11/2012 dwg - add BIOS_ADDR                      */
/* globals.h 3/11/2012 dwg - declarations common to all modules */
/****************************************************************/

#define CR 0x0d
#define LF 0x0a
#define ESC 27

#define BIOSAD  0x0e600
#define INFLSTV 1

#define MAXDRIVE 8

/*******************/
/* eof - globals.h */
/*******************/