OBJECTS = rndtest.com
OTHERS = *.obj *.OBJ *.asm *.hex *.lst *exec.*
DEST = ../../../../Binary/Apps/Test
TOOLS = ../../../../Tools

HITECHOBJS = rndtest.obj hbio.obj

include $(TOOLS)/Makefile.inc

rndtest.obj hbio.obj: hbio.h
