;
; CBIOS BUILD CONFIGURATION OPTIONS
;
CLRRAMDISK	.EQU	CLR_AUTO	; CLR_ALWAYS, CLR_NEVER, CLR_AUTO (CLEAR IF INVALID DIR AREA)
AUTOSUBMIT	.EQU	TRUE		; PROCESS PROFILE.SUB AT STARTUP
QPMTIMDAT	.EQU	TRUE		; SUPPORT QP/M TIMDAT ROUTINE
WRTCACHE	.EQU	TRUE		; ENABLE WRITE CACHING IN CBIOS (DE)BLOCKING ALGORITHM
DSKTRACE	.EQU	FALSE		; ENABLE TRACING OF CBIOS DISK FUNCTION CALLS
DEBUG		.EQU	FALSE		; MISCELLANEOUS DEBUG TRACING
;
CPM_LOC		.EQU	$D000		; LOCATION OF START OF CCP
;
#IFDEF PLTWBW
CPM_END		.EQU	$FE00		; ROMWBW HBIOS PROXY OCCUPIES TOP $280 BYTES OF MEMORY
#ENDIF
;
#IFDEF PLTUNA
CPM_END		.EQU	$FF00		; UNA UBIOS PROXY OCCUPIES TOP 1 PAGE OF MEMORY
#ENDIF
