;
; File:		ZDEPROP.Z80 - Default proportional width table for ZDE.
; Author:	Carson Wilson
; Date:		02 Jun 90
; Notes:	Assembles to a .HEX file which overlays ZDE's native table.

; EQUATES

TABLE	equ	????h		; Change "????" to the value given by ZDENSTAL
				; ..for "proportional table."
; 
	ORG	TABLE

;		Offset		  Corresponding character

	db	0		; space
	db	-12		; !
	db	0		; "
	db	0		; #
	db	0		; $
	db	6		; %
	db	6		; &
	db	-12		; '
	db	-6		; (
	db	-6		; )
	db	0		; *
	db	0		; +
	db	-12		; ,
	db	0		; -
	db	-12		; .
	db	0		; /
;
	db	0		; 0
	db	0		; 1
	db	0		; 2
	db	0		; 3
	db	0		; 4
	db	0		; 5
	db	0		; 6
	db	0		; 7
	db	0		; 8
	db	0		; 9
;
	db	-12		; :
	db	-12		; ;
	db	0		; <
	db	0		; =
	db	0		; >
	db	0		; ?
;
	db	6		; @
	db	6		; A
	db	6		; B
	db	6		; C
	db	6		; D
	db	6		; E
	db	6		; F
	db	6		; G
	db	6		; H
	db	-6		; I
	db	0		; J
	db	6		; K
	db	6		; L
	db	12		; M
	db	6		; N
	db	6		; O
	db	6		; P
	db	6		; Q
	db	6		; R
	db	6		; S
	db	6		; T
	db	12		; U
	db	6		; V
	db	12		; W
	db	6		; X
	db	6		; Y
	db	0		; Z
	db	-6		; [
	db	0		; \
	db	-6		; ]
	db	0		; ^
	db	0		; _
	db	-12		; `
;
	db	0		; a
	db	6		; b
	db	0		; c
	db	6		; d
	db	0		; e
	db	-6		; f
	db	6		; g
	db	6		; h
	db	-12		; i
	db	-6		; j
	db	6		; k
	db	-12		; l
	db	12		; m
	db	6		; n
	db	0		; o
	db	6		; p
	db	6		; q
	db	0		; r
	db	0		; s
	db	-6		; t
	db	6		; u
	db	6		; v
	db	12		; w
	db	0		; x
	db	6		; y
	db	0		; z
	db	-6		; {
	db	-12		; |
	db	-6		; }
	db	0		; ~

	end

; End ZDEPROP.Z80
