;
; Program:  CMDRUN
; Author:  Richard Conn
; Version: N/A
; Date: 11 June 84
;
TBUFF	EQU	80H
z3env	equ	0f400h

	ext	z3init
	ext	print,pstr

;
; Environment Definition
;
	if	z3env ne 0
;
; External ZCPR3 Environment Descriptor
;
	jmp	start
	db	'Z3ENV'	;This is a ZCPR3 Utility
	db	1	;External Environment Descriptor
z3eadr:
	dw	z3env
start:
	lhld	z3eadr	;pt to ZCPR3 environment
;
	else
;
; Internal ZCPR3 Environment Descriptor
;
	MACLIB	Z3BASE.LIB
	MACLIB	SYSENV.LIB
z3eadr:
	jmp	start
	SYSENV
start:
	lxi	h,z3eadr	;pt to ZCPR3 environment
	endif

;
; Start of Program -- Initialize ZCPR3 Environment
;
	call	z3init	;initialize the ZCPR3 Env and the VLIB Env
	CALL	PRINT
	DB	'Command Line: ',0
	LXI	H,TBUFF+1	;PT TO COMMAND LINE
	JMP	PSTR

	END
