OBJECTS = SysGen.com Survey.com \
	SysCopy.com Assign.com Format.com Talk.com Mode.com RTC.com \
	Timer.com IntTest.com
OTHERS = *.hex *.com
SUBDIRS = XM FDU FAT Tune
DEST = ../../Binary/Apps
TOOLS =../../Tools

include $(TOOLS)/Makefile.inc

USETASM = 1

Survey.com: USETASM=0

