OBJECTS = sysgen.com survey.com \
	syscopy.com assign.com format.com talk.com mode.com rtc.com \
	timer.com rtchb.com
SUBDIRS = XM FDU FAT Tune Test ZMP ZMD Dev VGM cpuspd
DEST = ../../Binary/Apps
TOOLS =../../Tools

include $(TOOLS)/Makefile.inc

USETASM = 1

survey.com: USETASM = 0

