SUBDIRS = HTalk XM FDU FAT Tune Test ZMP ZMD Dev VGM cpuspd reboot Survey BBCBASIC copysl \
	slabel sysgen syscopy assign format talk mode rtc timer ZDE
TOOLS =../../Tools

include $(TOOLS)/Makefile.inc
