;
;--------------------------------------------------------------------------------------------------
;   BF_I2C HAL -- I2C FUNCTION TABLE AND BACKEND-FACING (BF) FUNCTION BODIES
;--------------------------------------------------------------------------------------------------
;
; HBIOS I2C BUS UNIT TABLE. ONE ENTRY, WRITTEN AS A LITERAL SINCE
; I2CPCFENABLE/I2CBITENABLE ARE MUTUALLY EXCLUSIVE AT THIS TIME.
; AT MOST ONE BACKEND EXISTS, KNOWN AT ASSEMBLE TIME, NOT DISCOVERED AT BOOT.
;
I2C_FNCNT	.EQU	8		; NUMBER OF I2C FUNCS (FOR RANGE CHECK)
I2C_MAX		.EQU	1		; ONLY ONE LOGICAL I2C BUS
;
		.DB	I2C_FNCNT	; I2C FUNCTION COUNT (FOR RANGE CHECK)
		.DB	I2C_MAX		; MAX ENTRY COUNT TABLE PREFIX
#IF (I2CPCFENABLE | I2CBITENABLE)
I2C_CNT		.DB	1		; ONE ENTRY, KNOWN AT ASSEMBLE TIME
I2C_TBL		.DW	I2C_FNTBL, I2C_IDAT
#ELSE
I2C_CNT		.DB	0		; NO BACKEND, HB_UNITERR ON ANY CALL
I2C_TBL		.DW	0, 0
#ENDIF
;
#IF (I2CPCFENABLE | I2CBITENABLE)
;
I2C_FNTBL:
	.DW	I2C_BF_DEVICE
	.DW	I2C_BF_START
	.DW	I2C_BF_REPSTART
	.DW	I2C_BF_WRITE
	.DW	I2C_BF_READ
	.DW	I2C_BF_XFER
	.DW	I2C_BF_BUSBUSY
	.DW	I2C_BF_STOP
;
#IF (($ - I2C_FNTBL) != (I2C_FNCNT * 2))
	.ECHO	"*** INVALID I2C FUNCTION TABLE ***\n"
	!!!!!
#ENDIF
;
; I2C INSTANCE DATA OFFSETS
I2C_DAT_BACKEND	.EQU	0		; BACKEND ID: 1=PCF8584, 2=BITBANG (BYTE)
;
; LOW BYTE IS THE REAL BASE I/O ADDRESS
; HIGH BYTE FOR FUTURE EXPANSION (MULTIPLEXER?)
I2C_DAT_IOBASE	.EQU	1		; BASE I/O ADDRESS (WORD)
I2C_DAT_SIZ	.EQU	3		; TOTAL SIZE OF I2C INSTANCE DATA
;
#IF (I2CPCFENABLE)
I2C_IDAT:
	.DB	1			; BACKEND: PCF8584
	.DW	I2CPCF_BASE
#ENDIF
#IF (I2CBITENABLE)
I2C_IDAT:
	.DB	2			; BACKEND: BITBANG
	.DW	I2CBIT_BASE
#ENDIF
;
; REPORT I2C BUS-MASTER PRESENCE/IDENTITY. BACKEND/BASE PORT ARE READ FROM
; THIS UNIT'S I2C_IDAT ENTRY, NOT HARDCODED HERE.
; PRESENCE CHECK USES I2C_FAIL_FLAG, SET WHEN THE BUS-MASTER CHIP FAILED
; ITS OWN SELF-CHECK, SO A FAILED BUS-MASTER HONESTLY REPORTS NOT PRESENT.
;   EXIT:
;     A=STATUS (0=PRESENT, ERR_NOHW=BUS-MASTER INIT FAILED),
;     B=BACKEND (1=PCF8584, 2=BITBANG), HL=BASE IO PORT
;
I2C_BF_DEVICE:
	LD	A,(I2C_FAIL_FLAG)
	OR	A
	RET	NZ			; BUS-MASTER INIT FAILED
	LD	A,(IY+I2C_DAT_BACKEND)
	LD	B,A
	LD	L,(IY+I2C_DAT_IOBASE)
	LD	H,(IY+I2C_DAT_IOBASE+1)
	XOR	A
	RET
;
; ISSUE A START CONDITION PLUS THE ADDRESS BYTE. CHECKS I2C_FAIL_FLAG
; FIRST, THEN WAITS FOR BUS-FREE. ADDRESS ARRIVES IN E, NOT A.
; NEITHER CHECK TOUCHES E, SO NO SAVE/RESTORE IS NEEDED.
;   ENTRY:
;     E=7 BIT ADDRESS, R/W IN BIT 0
;   EXIT:
;     A=STATUS (0=OK, 1=NAK, 3=BUS NOT IDLE, ERR_NOHW=BUS-MASTER INIT FAILED,
;     0FFH=TIMEOUT)
;
I2C_BF_START:
	LD	A,(I2C_FAIL_FLAG)
	OR	A
	RET	NZ			; BUS-MASTER INIT FAILED
	CALL	I2C_WAIT_FOR_BB
	JR	NZ,I2C_BF_START_BUSY
	LD	A,E			; ADDRESS BYTE
	CALL	I2C_START_ADDR
	JP	I2C_WAIT_FOR_ACK	; A=STATUS ON RETURN (0=OK, 1=NAK, 0FFH=TIMEOUT)
I2C_BF_START_BUSY:
	LD	A,3			; BUS NEVER WENT IDLE
	OR	A
	RET
;
; ISSUE A REPEATED START PLUS THE ADDRESS BYTE
;   ENTRY:
;     E=7 BIT ADDRESS, R/W IN BIT 0
;   EXIT:
;     A=STATUS (0=OK, 1=NAK, 0FFH=TIMEOUT)
;
I2C_BF_REPSTART:
	CALL	I2C_REPSTART
	LD	A,E			; ADDRESS BYTE
	CALL	I2C_PUTBYTE
	JP	I2C_WAIT_FOR_ACK
;
; WRITE ONE DATA BYTE AND WAIT FOR ACK
;   ENTRY:
;     E=DATA BYTE
;   EXIT:
;     A=STATUS (0=OK, 1=NAK, 0FFH=TIMEOUT)
;
I2C_BF_WRITE:
	LD	A,E			; DATA BYTE
	JP	I2C_PUTBYTE_ACK
;
; READ ONE DATA BYTE. ON THE LAST BYTE OF A READ, PREP A NACK FIRST
; NO ACK IS EXPECTED BACK, SO WAIT ON PIN ONLY OTHERWISE WAIT FOR ACK.
;   ENTRY:
;     E=1 IF THIS IS THE LAST BYTE OF THE READ (SEND NACK), ELSE 0
;   EXIT:
;     A=STATUS (0=OK, 0FFH=TIMEOUT), L=DATA BYTE
;
I2C_BF_READ:
	LD	A,E
	OR	A
	JR	Z,I2C_BF_READ_MID
	CALL	I2C_PREPNACK
	PUSH	BC			; I2C_WAIT_FOR_PIN CLOBBERS B, NEVER RESTORES IT
	CALL	I2C_WAIT_FOR_PIN
	POP	BC
	JR	I2C_BF_READ_GET
I2C_BF_READ_MID:
	CALL	I2C_WAIT_FOR_ACK
I2C_BF_READ_GET:
	OR	A
	RET	NZ			; FAIL A ALREADY HOLDS NONZERO STATUS
	CALL	I2C_GETBYTE
	LD	L,A
	XOR	A
	RET
;
; TRANSFER E BYTES FROM A (POSSIBLY BANKED) CALLER BUFFER, WRITE-ONLY.
; CALLER'S BUFFER MAY BE IN A DIFFERENT BANK THAN HBIOS ITSELF, SO IT'S
; COPIED INTO A STAGING BUFFER VIA HBX_BNKCPY FIRST.
;   ENTRY:
;     C=0, E=BYTE COUNT (0-255, 0 MEANS 256), D=BUFFER BANK, HL=BUFFER
;   EXIT:
;     A=STATUS (0=OK, 1=NAK, 0FFH=TIMEOUT), E=BYTES SUCCESSFULLY SENT
;     (0 MEANS 256 ONLY IF A=0, ELSE 0 MEANS NONE SENT)
;
I2C_BF_XFER:
	LD	A,D			; CALLER'S BUFFER BANK (SOURCE)
	LD	(HB_SRCBNK),A
	LD	A,BID_BIOS		; STAGING BUFFER BANK (DEST)
	LD	(HB_DSTBNK),A
	LD	B,0
	LD	C,E			; BC = BYTE COUNT
	PUSH	BC
	LD	DE,I2C_XFER_STAGEBUF
	CALL	HBX_BNKCPY		; HL(CALLER BUF) -> DE(STAGEBUF), BC BYTES
	POP	BC
;
	LD	HL,I2C_XFER_STAGEBUF	; WRITE FROM OUR STAGING BUFFER
	LD	B,C			; B = LOOP COUNTER (DJNZ NEEDS IT IN B), C KEPT
					; UNTOUCHED AS THE ORIGINAL TOTAL COUNT
I2C_BF_XFER_LOOP:
	LD	A,(HL)
	PUSH	HL
	PUSH	BC
	CALL	I2C_PUTBYTE_ACK
	POP	BC
	POP	HL
	JR	NZ,I2C_BF_XFER_FAIL
	INC	HL
	DJNZ	I2C_BF_XFER_LOOP
	LD	E,C			; ALL BYTES SENT
	XOR	A
	RET
I2C_BF_XFER_FAIL:
	PUSH	AF			; SAVE STATUS, SUB BELOW CLOBBERS FLAGS
	LD	A,C
	SUB	B			; BYTES SENT BEFORE THIS FAILURE
	LD	E,A
	POP	AF
	RET
;
I2C_XFER_STAGEBUF:
	.FILL	255,0
;
; NON-BLOCKING BUS-BUSY CHECK. DOES NOT WAIT, JUST REPORTS CURRENT STATE.
; REUSES STATUS CODE 3 FROM BF_I2CSTART'S "BUS NEVER WENT IDLE" CASE, SAME
; MEANING HERE: BUS IS BUSY. UNLIKE REPSTART/WRITE/XFER, THIS CAN BE
; CALLED STANDALONE WITHOUT A PRIOR START, SO IT CHECKS I2C_FAIL_FLAG
; ITSELF RATHER THAN RELYING ON A PRECEDING START TO HAVE CAUGHT IT.
;   EXIT:
;     A=STATUS (0=FREE, 3=BUSY, ERR_NOHW=BUS-MASTER INIT FAILED)
;
I2C_BF_BUSBUSY:
	LD	A,(I2C_FAIL_FLAG)
	OR	A
	RET	NZ			; BUS-MASTER INIT FAILED
	CALL	I2C_CHECK_BB
	JR	NZ,I2C_BF_BUSBUSY_FREE
	LD	A,3
	OR	A
	RET
I2C_BF_BUSBUSY_FREE:
	XOR	A
	RET
;
; ISSUE A STOP CONDITION. SOME DEVICES NEED TWO STOPS IN SUCCESSION TO
; FULLY CLEAR THEIR INTERNAL STATE AFTER CERTAIN TRANSACTIONS.
;   ENTRY:
;     E=1 FOR DOUBLE STOP, 0 FOR SINGLE
;   EXIT:
;     A=STATUS (ALWAYS 0)
;
I2C_BF_STOP:
	CALL	I2C_STOP
	LD	A,E
	OR	A
	JR	Z,I2C_BF_STOP_DONE
	CALL	I2C_STOP
I2C_BF_STOP_DONE:
	XOR	A
	RET
;
#ENDIF
