;
;==================================================================================================
; HARDWARE SUPPORT FOR FRONT PANELS
;==================================================================================================
;
; EMIT FRONT PANEL CONFIGURATION TO ASSEMBLY OUTPUT
;
	DEVECHO	"FP: "
#IF (FP_USE_I2C)
	DEVECHO	"I2C ADDR="
	DEVECHO	FP_I2CADR
#ELSE
  #IF (FPLED_ENABLE)
	DEVECHO	"LEDIO="
	DEVECHO	FPLED_IO
  #ENDIF
  #IF (FPLED_ENABLE & FPSW_ENABLE)
	DEVECHO	", "
  #ENDIF
  #IF (FPSW_ENABLE)
	DEVECHO	"SWIO="
	DEVECHO	FPSW_IO
  #ENDIF
#ENDIF
	DEVECHO	"\n"
;
#IF (FP_USE_I2C & !(I2CPCFENABLE | I2CBITENABLE))
	.ECHO	"*** ERROR: FP_USE_I2C REQUIRES I2CPCFENABLE OR I2CBITENABLE!!!\n"
	!!!	; FORCE AN ASSEMBLY ERROR
#ENDIF
;
#IF (FP_USE_I2C)
; 7-BIT MODULE ADDRESS, PRESHIFTED WITH R/W BIT
FP_I2CADR_W	.EQU	FP_I2CADR << 1
FP_I2CADR_R	.EQU	(FP_I2CADR << 1) | 1
;
; TCA9555 COMMAND BYTES
;
FP_TCA_IN0	.EQU	$00		; INPUT PORT 0 -- SWITCHES
FP_TCA_OUT1	.EQU	$03		; OUTPUT PORT 1 -- LEDS
FP_TCA_CFG0	.EQU	$06		; CONFIGURATION PORT 0
FP_TCA_CFG1	.EQU	$07		; CONFIGURATION PORT 1
#ENDIF
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE HEADER
;--------------------------------------------------------------------------------------------------
;
ORG_FP	.EQU	$
;
	.DW	SIZ_FP			; MODULE SIZE
	.DW	FP_INITPHASE		; ADR OF INIT PHASE HANDLER
;
FP_INITPHASE:
	; INIT PHASE HANDLER, A=PHASE
	CP	HB_PHASE_PREINIT	; PREINIT PHASE?
	JP	Z,FP_PREINIT		; DO PREINIT
	CP	HB_PHASE_INIT		; INIT PHASE?
	JP	Z,FP_INIT		; DO INIT
	RET				; DONE
;
; PRECONSOLE CONSOLE INITIALIZATION
;
FP_PREINIT:
;
; FRONT PANEL HARDWARE DETECTION
;
; WE ARE REALLY JUST CHECKING FOR SWITCHES.  NO WAY TO QUERY FOR
; LEDS.  WE CHECK FOR I/O CONFLICT WITH VGARC IF ACTIVE.
;
; UNDER FP_USE_I2C, LEDS AND SWITCHES ARE BOTH ON ONE TCA9555, SO ONE
; PRESENCE PROBE COVERS BOTH, SAME I2C-ACK TECHNIQUE AS Z_DETECT IN
; lcdi2c.asm.
;
	; D: LEDS ACTIVE, E: SWITCHES ACTIVE
#IF (FP_USE_I2C)
	LD	DE,$0000		; ASSUME NOT PRESENT, PROVEN BELOW
;
	; *** SHOULD THERE BE A CALL TO I2C_ENSURE_INIT HERE? ***
;
	LD	A,(I2C_FAIL_FLAG)	; I2C ITSELF MUST BE WORKING FIRST --
	OR	A			; NO POINT PROBING OVER A DEAD BUS MASTER
	JR	NZ,FP_PREINITZ
;
	LD	E,FP_I2CADR_W
	CALL	I2C_BF_START
	PUSH	AF
	LD	E,0
	CALL	I2C_BF_STOP
	POP	AF
	JR	NZ,FP_PREINITZ		; NO ACK, TCA9555 NOT PRESENT
;
	CALL	FP_TCA_INIT		; P0=INPUT (SWITCHES), P1=OUTPUT (LEDS)
	JR	NZ,FP_PREINITZ		; CONFIG WRITE FAILED, TREAT AS NOT PRESENT
;
	LD	D,TRUE
	LD	E,TRUE
	JR	FP_PREINITZ
#ELSE
	LD	D,FPLED_ENABLE			; DEFAULT FOR LEDS
	LD	E,FPSW_ENABLE			; DEFAULT FOR SWITCHES
;
  #IF (FPSW_ENABLE)
	; THE SWITCH HARDWARE MAY OR MAY NOT BE INSTALLED.  SO, HERE WE
	; ATTEMPT TO CONFIRM WE HAVE A VALID PORT.  CREDIT TO STEPHEN
	; COUSINS FOR THIS APPROACH.
	LD	C,FPSW_IO		; ADR OF SWITCH PORT
	EZ80_IO
	IN	C,(C)			; READ IT USING IN (C)
	EZ80_IO
	IN	A,(FPSW_IO)		; READ IT USING IN (PORT)
	CP	C			; PORT FLOATING ON MISMATCH
	JR	NZ,FP_PREINIT1		; NO H/W, SET FLAG
	CP	$FF			; PORT FLOATING ON $FF
	JR	Z,FP_PREINIT1		; NO H/W, SET FLAG
	JR	FP_PREINITZ		; H/W EXISTS, DONE
;
FP_PREINIT1:
	LD	E,FALSE			; RECORD NOT PRESENT
  #ENDIF
#ENDIF
;
FP_PREINITZ:
	LD	(FP_ACTIVE),DE		; RECORD RESULTS
	RET				; DONE
;
#IF (FP_USE_I2C)
;
; ONE-TIME TCA9555 CONFIG
; P0 (SWITCHES) = INPUT
; P1 (LEDS) = OUTPUT
; TCA9555 DEFAULTS BOTH PORTS TO INPUT AT POWER-ON, SO THIS MUST RUN
; BEFORE THE FIRST FP_SETLEDS CALL OR THE LEDS STAY HIGH-IMPEDANCE.
; RETURNS Z ON SUCCESS.
;
FP_TCA_INIT:
	LD	E,FP_I2CADR_W
	CALL	I2C_BF_START
	JR	NZ,FP_TCA_INIT_STOP
	LD	E,FP_TCA_CFG0
	CALL	I2C_BF_WRITE
	JR	NZ,FP_TCA_INIT_STOP
	LD	E,$FF			; P0 = ALL INPUT
	CALL	I2C_BF_WRITE
FP_TCA_INIT_STOP:
	PUSH	AF
	LD	E,0
	CALL	I2C_BF_STOP
	POP	AF
	RET	NZ
;
	LD	E,FP_I2CADR_W
	CALL	I2C_BF_START
	JR	NZ,FP_TCA_INIT_STOP2
	LD	E,FP_TCA_CFG1
	CALL	I2C_BF_WRITE
	JR	NZ,FP_TCA_INIT_STOP2
	LD	E,$00			; P1 = ALL OUTPUT
	CALL	I2C_BF_WRITE
FP_TCA_INIT_STOP2:
	PUSH	AF
	LD	E,0
	CALL	I2C_BF_STOP
	POP	AF
	RET
;
; LAZY WRAPPER AROUND FP_TCA_INIT. LETS AN EARLY, PRE-MODINIT FPLEDS()
; CALL TRIGGER THE ONE-TIME P0/P1 CONFIG ON DEMAND. RETRIES EVERY CALL
; UNTIL IT SUCCEEDS ONCE, THEN LATCHES AND SKIPS FUTURE WORK.
;
FP_TCA_ENSURE_CFG:
	LD	A,(FP_TCA_CFGPENDING)
	OR	A
	RET	Z			; ALREADY CONFIGURED -- FLAG ALREADY 0, Z ALREADY SET
	CALL	FP_TCA_INIT
	RET	NZ			; FAILED, LEAVE FLAG SET SO WE RETRY NEXT CALL
	XOR	A
	LD	(FP_TCA_CFGPENDING),A
	RET				; FLAGS STILL Z FROM THE XOR ABOVE
;
FP_TCA_CFGPENDING	.DB	TRUE
;
#ENDIF
;
; POST CONSOLE INITIALIZATION
;
FP_INIT:
	PRTS("\r\nFP:$")
#IF (FP_USE_I2C)
	PRTS(" I2C ADDR=0x$")
	LD	A,FP_I2CADR
	CALL	PRTHEXBYTE
#ELSE
  #IF (FPLED_ENABLE)
	PRTS(" LEDS IO=0x$")
	LD	A,FPLED_IO
	CALL	PRTHEXBYTE
	LD	A,(FPLED_ACTIVE)
	CALL	FP_ACTSTR
  #ENDIF
;
  #IF (FPSW_ENABLE)
	PRTS(" SWITCHES$")
	PRTS(" IO=0x$")
	LD	A,FPSW_IO
	CALL	PRTHEXBYTE
	LD	A,(FPSW_ACTIVE)
	CALL	FP_ACTSTR
  #ENDIF
#ENDIF
;
#IF (FPSW_ENABLE)
	LD	A,(FPSW_ACTIVE)		; GET FP EXISTENCE FLAG
	OR	A			; SET FLAGS
	RET	Z			; DONE IF NOT THERE
;
	PRTS(" VALUE=0x$")		; TAG
	CALL	FP_GETSWITCHES		; GET SWITCH SETTINGS
	CALL	PRTHEXBYTE		; DISPLAY VALUE
#ENDIF
;
	RET
;
FP_ACTSTR:
	CALL	PC_SPACE
	OR	A			; SET FLAGS
	JR	NZ,FP_ACTSTR1		; IF ACTIVE, SKIP "IN" PREFIX
	PRTS("IN$")
FP_ACTSTR1:
	PRTS("ACTIVE$")
	RET
;
#IF (FPLED_ENABLE)
;
; SET FRONT PANEL LEDS FROM VALUE IN A
;
FP_SETLEDS:
	PUSH	AF			; PRESERVE CALLER'S A/FLAGS
	PUSH	HL			; SAVE HL
	LD	L,A			; LED VALUE TO L
	LD	A,(FPLED_ACTIVE)	; LEDS ACTIVE?
	OR	A			; SET FLAGS
	LD	A,L			; RESTORE REG A
	JR	Z,FP_SETLEDS1		; BAIL OUT IF NOT ACTIVE
;
  #IF (FPLED_INV)
	XOR	$FF			; INVERT BITS IF NEEDED -- SAME FLAG EITHER WAY,
  #ENDIF				; ONLY ONE OF THE TWO LEGS BELOW IS EVER BUILT
  #IF (FP_USE_I2C)
	LD	L,A			; STASH BYTE TO SEND ACROSS BUS-MASTER CALLS
	CALL	I2C_ENSURE_INIT		; SAFE PRE-MODINIT TOO -- REAL WORK ONCE ONLY
	JR	NZ,FP_SETLEDS1		; I2C BUS MASTER ITSELF NOT WORKING, GIVE UP QUIETLY
	CALL	FP_TCA_ENSURE_CFG	; ONE-TIME P0=IN/P1=OUT DIRECTION CONFIG
	JR	NZ,FP_SETLEDS1
	LD	E,FP_I2CADR_W
	CALL	I2C_BF_START
	JR	NZ,FP_SETLEDS_STOP	; NO ACK, MODULE GONE, STILL RELEASE BUS
	LD	E,FP_TCA_OUT1		; SELECT OUTPUT PORT 1 (LEDS)
	CALL	I2C_BF_WRITE
	JR	NZ,FP_SETLEDS_STOP
	LD	E,L
	CALL	I2C_BF_WRITE
FP_SETLEDS_STOP:
	LD	E,0
	CALL	I2C_BF_STOP
  #ELSE
	EZ80_IO
	OUT	(FPLED_IO),A		; WRITE
  #ENDIF
FP_SETLEDS1:
	POP	HL			; RESTORE HL
	POP	AF			; RESTORE CALLER'S A/FLAGS
	RET				; DONE
;
#ENDIF
;
#IF (FPSW_ENABLE)
;
; GET FRONT PANEL SWITCH SETTINGS
;
FP_GETSWITCHES:
	LD	A,(FPSW_ACTIVE)		; SWITCHES ACTIVE?
	OR	A			; SET FLAGS
	RET	Z			; BAIL OUT IF NOT ACTIVE
  #IF (FP_USE_I2C)
	LD	E,FP_I2CADR_W
	CALL	I2C_BF_START
	JR	NZ,FP_GETSWITCHES_STOP	; NO ACK, MODULE GONE
	LD	E,FP_TCA_IN0		; SELECT INPUT PORT 0 (SWITCHES)
	CALL	I2C_BF_WRITE
	JR	NZ,FP_GETSWITCHES_STOP
	LD	E,FP_I2CADR_R
	CALL	I2C_BF_REPSTART		; SWITCH TO READ DIRECTION, SAME DEVICE
	JR	NZ,FP_GETSWITCHES_STOP
	LD	E,1			; NACK, SINGLE BYTE
	CALL	I2C_BF_READ		; L=SWITCH BYTE
	JR	NZ,FP_GETSWITCHES_STOP
	LD	A,L
	PUSH	AF
	LD	E,0
	CALL	I2C_BF_STOP
	POP	AF
	JR	FP_GETSWITCHES_INV
FP_GETSWITCHES_STOP:
	LD	E,0
	CALL	I2C_BF_STOP
FP_GETSWITCHES_NONE:
	XOR	A
FP_GETSWITCHES_INV:
  #ELSE
	EZ80_IO
	IN	A,(FPSW_IO)		; READ SWITCHES
  #ENDIF
  #IF (FPSW_INV)
	XOR	$FF			; INVERT BITS IF NEEDED
  #ENDIF
	RET				; DONE
#ENDIF
;
FP_ACTIVE:
FPSW_ACTIVE	.DB	TRUE
FPLED_ACTIVE	.DB	TRUE
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE TRAILER
;--------------------------------------------------------------------------------------------------
;
END_FP	.EQU	$
SIZ_FP	.EQU	END_FP - ORG_FP
;	
	MEMECHO	"FP occupies "
	MEMECHO	SIZ_FP
	MEMECHO	" bytes.\n"
