;==================================================================================================
; EZ80 ON-CHIP I2C CONTROLLER BUS MASTER
;
; DROP IN REPLACEMENT FOR I2CPCF.ASM/I2CBIT.ASM, SAME PUBLIC LABELS.
; SELECTED VIA I2CEZ80ENABLE. AT MOST ONE I2C BUS MASTER DRIVER (SEE I2CENABLE IN std.asm).
; POLLED MASTER, 100KHZ. STATUS CODES PER PS0153 TABLES 78-82.
;
; THE REGISTERS ARE ON-CHIP AT $00C8-$00CD, ACCESSED WITH IN0/OUT0.
;
; RESULT CODES:
;   0=OK, 1=NAK, 2=BUS ERROR, 4=LOST ARBITRATION, 0FFH=TIMEOUT
;
#IF (CPUFAM != CPU_EZ80)
	.ECHO	"*** I2CEZ80 DRIVER REQUIRES AN EZ80 CPU!!!\n"
	!!!	; FORCE AN ASSEMBLY ERROR
#ENDIF
;
I2CEZ80_BASE	.EQU	$C8
I2CEZ80_SAR	.EQU	I2CEZ80_BASE+0	; OWN SLAVE ADDRESS
I2CEZ80_XSAR	.EQU	I2CEZ80_BASE+1	; EXTENDED SLAVE ADDRESS
I2CEZ80_DR	.EQU	I2CEZ80_BASE+2	; DATA
I2CEZ80_CTL	.EQU	I2CEZ80_BASE+3	; CONTROL
I2CEZ80_SR	.EQU	I2CEZ80_BASE+4	; READ: STATUS
I2CEZ80_CCR	.EQU	I2CEZ80_BASE+4	; WRITE: CLOCK CONTROL
I2CEZ80_SRR	.EQU	I2CEZ80_BASE+5	; WRITE ANY VALUE: SOFTWARE RESET
I2CEZ80_PPD1	.EQU	$DB		; CLK_PPD1, PERIPHERAL CLOCK POWER-DOWN
;
I2CEZ80_ENAB	.EQU	01000000B	; I2C_CTL: SCL/SDA ENABLED
I2CEZ80_STA	.EQU	00100000B	; I2C_CTL: SEND (REPEATED) START
I2CEZ80_STP	.EQU	00010000B	; I2C_CTL: SEND STOP, SELF-CLEARING
I2CEZ80_IFLG	.EQU	00001000B	; I2C_CTL: STEP DONE, SCL HELD LOW
I2CEZ80_AAK	.EQU	00000100B	; I2C_CTL: ACK THE NEXT RECEIVED BYTE
I2CEZ80_I2COFF	.EQU	00000100B	; CLK_PPD1: I2C CLOCK OFF
;
I2CEZ80_IDLE	.EQU	$F8		; I2C_SR: NOTHING PENDING
;
; FSCL = CPUOSC / (10 * (M+1) * 2^N), M ROUNDED UP SO SCL NEVER EXCEEDS 100KHZ
;
I2CEZ80_N	.EQU	2
I2CEZ80_M	.EQU	((CPUOSC + 3999999) / 4000000) - 1
#IF (I2CEZ80_M > 15)
	.ECHO	"*** I2CEZ80: CPUOSC TOO HIGH FOR 100KHZ WITH N=2!!!\n"
	!!!	; FORCE AN ASSEMBLY ERROR
#ENDIF
I2CEZ80_CCRVAL	.EQU	(I2CEZ80_M << 3) | I2CEZ80_N
;
I2CEZ80_TO	.EQU	65000		; IFLG/STP POLL LIMIT
;
I2CEZ80_OK	.EQU	0
I2CEZ80_NAK	.EQU	1
I2CEZ80_BER	.EQU	2
I2CEZ80_ARB	.EQU	4
I2CEZ80_TMO	.EQU	$FF
;
	DEVECHO	"I2CEZ80: IO="
	DEVECHO	I2CEZ80_BASE
	DEVECHO	"\n"
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE HEADER
;--------------------------------------------------------------------------------------------------
;
ORG_I2CEZ80	.EQU	$
;
	.DW	SIZ_I2CEZ80		; MODULE SIZE
	.DW	I2CEZ80_INITPHASE	; ADR OF INIT PHASE HANDLER
;
I2CEZ80_INITPHASE:
	CP	HB_PHASE_INIT		; INIT PHASE?
	JP	Z,I2CEZ80_INIT		; DO INIT
	RET				; DONE
;
;-----------------------------------------------------------------------------
;
I2CEZ80_INIT:
	CALL	NEWLINE
	PRTS("I2CEZ80: IO=0x$")
	LD	A,I2CEZ80_BASE
	CALL	PRTHEXBYTE
	CALL	PC_SPACE
	CALL	I2C_ENSURE_INIT
	RET	Z				; SUCCESS
	LD	HL,(I2CEZ80_FAIL_MSG)		; PRINT THE RECORDED FAILURE REASON
	CALL	PRTSTR
	RET
;
; CLOCK ON, RESET, NO OWN SLAVE ADDRESS, THEN CHECK FOR IDLE. Z IF OK.
;
I2CEZ80_INITDEV:
	IN0_A(I2CEZ80_PPD1)
	AND	~I2CEZ80_I2COFF & $FF	; ENSURE THE I2C CLOCK IS ON
	OUT0_A(I2CEZ80_PPD1)
	CALL	I2CEZ80_RESET
	XOR	A
	OUT0_A(I2CEZ80_SAR)		; NO OWN ADDRESS, NO GENERAL CALL
	OUT0_A(I2CEZ80_XSAR)
	IN0_A(I2CEZ80_SR)
	CP	I2CEZ80_IDLE
	JR	NZ,I2CEZ80_FAIL
	XOR	A
	RET
;
I2CEZ80_FAIL:
	PUSH	HL
	LD	HL,I2CEZ80_NOI2C
	JP	I2C_RECORDFAIL
;
I2C_FAIL_FLAG:
	.DB	0
;
I2CEZ80_FAIL_MSG:
	.DW	0
;
I2CEZ80_INITDONE:
	.DB	FALSE
;
I2C_ENSURE_INIT:
	LD	A,(I2CEZ80_INITDONE)
	OR	A
	JR	Z,I2C_ENSURE_INIT1	; NOT DONE YET
	XOR	A			; ALREADY SUCCEEDED, FORCE Z
	RET
I2C_ENSURE_INIT1:
	CALL	I2CEZ80_INITDEV
	RET	NZ			; FAILED, LEAVE UNCACHED SO WE RETRY NEXT CALL
	LD	A,TRUE
	LD	(I2CEZ80_INITDONE),A
	XOR	A			; ENSURE Z SET
	RET
;
;-----------------------------------------------------------------------------
; SOFTWARE RESET TO IDLE. CCR IS NOT DOCUMENTED TO SURVIVE IT.
; PRESERVES BC, DE, HL.
;
I2CEZ80_RESET:
	OUT0_A(I2CEZ80_SRR)
	LD	A,I2CEZ80_CCRVAL
	OUT0_A(I2CEZ80_CCR)
	LD	A,I2CEZ80_ENAB
	OUT0_A(I2CEZ80_CTL)
	RET
;
;-----------------------------------------------------------------------------
; ONE BUS STEP: WRITE I2C_CTL (A, IFLG=0), WAIT FOR IFLG, CLASSIFY I2C_SR.
; BUS ERROR AND LOST ARBITRATION ARE ABORTED TO IDLE WITH STP.
; RETURN A=RESULT CODE, ALSO IN I2CEZ80_RESULT, Z IF OK.
; PRESERVES BC, DE, HL.
;
I2CEZ80_STEP:
	OUT0_A(I2CEZ80_CTL)
	PUSH	HL
	LD	HL,I2CEZ80_TO
I2CEZ80_STEP1:
	IN0_A(I2CEZ80_CTL)
	AND	I2CEZ80_IFLG
	JR	NZ,I2CEZ80_STEP2
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,I2CEZ80_STEP1
	POP	HL
	CALL	I2CEZ80_RESET
	LD	A,I2CEZ80_TMO
	JR	I2CEZ80_SETRES
;
I2CEZ80_STEP2:
	PUSH	BC
	IN0_A(I2CEZ80_SR)
	LD	C,A
	LD	HL,I2CEZ80_CODES
I2CEZ80_STEP3:
	LD	A,(HL)
	CP	$FF			; END OF TABLE
	JR	Z,I2CEZ80_STEP4
	INC	HL
	CP	C
	LD	A,(HL)			; RESULT FOR THIS CODE, FLAGS FROM CP
	INC	HL
	JR	NZ,I2CEZ80_STEP3
	CP	I2CEZ80_BER
	JR	C,I2CEZ80_STEP5		; OK OR NAK
	JR	I2CEZ80_STEP6
I2CEZ80_STEP4:
	LD	A,I2CEZ80_BER		; 00H OR ANY STATE A MASTER SHOULD NEVER SEE
I2CEZ80_STEP6:
	PUSH	AF
	LD	A,I2CEZ80_ENAB | I2CEZ80_STP
	OUT0_A(I2CEZ80_CTL)
	POP	AF
I2CEZ80_STEP5:
	POP	BC
	POP	HL
I2CEZ80_SETRES:
	LD	(I2CEZ80_RESULT),A
	OR	A
	RET
;
; MASTER STATUS CODES AND THEIR RESULT CODE
;
I2CEZ80_CODES:
	.DB	$08,I2CEZ80_OK		; START SENT
	.DB	$10,I2CEZ80_OK		; REPEATED START SENT
	.DB	$18,I2CEZ80_OK		; SLA+W, ACK
	.DB	$28,I2CEZ80_OK		; DATA SENT, ACK
	.DB	$40,I2CEZ80_OK		; SLA+R, ACK
	.DB	$50,I2CEZ80_OK		; DATA RECEIVED, ACK SENT
	.DB	$58,I2CEZ80_OK		; DATA RECEIVED, NACK SENT
	.DB	$20,I2CEZ80_NAK		; SLA+W, NO ACK
	.DB	$30,I2CEZ80_NAK		; DATA SENT, NO ACK
	.DB	$48,I2CEZ80_NAK		; SLA+R, NO ACK
	.DB	$38,I2CEZ80_ARB		; ARBITRATION LOST
	.DB	$68,I2CEZ80_ARB		; ARBITRATION LOST, ADDRESSED AS SLAVE (W)
	.DB	$78,I2CEZ80_ARB		; ARBITRATION LOST, GENERAL CALL
	.DB	$B0,I2CEZ80_ARB		; ARBITRATION LOST, ADDRESSED AS SLAVE (R)
	.DB	$FF
;
;-----------------------------------------------------------------------------
; Z, A=0 IF THE TRANSACTION IS STILL GOING. NZ, A=RESULT IF AN EARLIER STEP
; ENDED IT (BUS ERROR, LOST ARBITRATION, TIMEOUT).
;
I2CEZ80_ALIVE:
	LD	A,(I2CEZ80_RESULT)
	CP	I2CEZ80_BER
	JR	NC,I2CEZ80_ALIVE1
	XOR	A
	RET
I2CEZ80_ALIVE1:
	OR	A			; RESULT IS NONZERO, FORCE NZ
	RET
;
;-----------------------------------------------------------------------------
; START, THEN THE ADDRESS BYTE IN A. STA WAITS FOR A FREE BUS ITSELF.
;
I2C_START_ADDR:
	LD	(I2CEZ80_BYTE),A
	XOR	A
	LD	(I2CEZ80_NACKPEND),A
	LD	A,I2CEZ80_ENAB | I2CEZ80_STA
	CALL	I2CEZ80_STEP		; 08H
	RET	NZ
	JR	I2CEZ80_PUT
;
;-----------------------------------------------------------------------------
; REPEATED START, THE CALLER SENDS THE ADDRESS BYTE WITH I2C_PUTBYTE
;
I2C_REPSTART:
	CALL	I2CEZ80_ALIVE
	RET	NZ
	LD	A,I2CEZ80_ENAB | I2CEZ80_STA
	JP	I2CEZ80_STEP		; 10H
;
;-----------------------------------------------------------------------------
; STOP, WAITS UNTIL STP CLEARS. PRESERVES BC, DE, HL.
;
I2C_STOP:
	LD	A,I2CEZ80_ENAB | I2CEZ80_STP
	OUT0_A(I2CEZ80_CTL)
	PUSH	HL
	LD	HL,I2CEZ80_TO
I2C_STOP1:
	IN0_A(I2CEZ80_CTL)
	AND	I2CEZ80_STP
	JR	Z,I2C_STOP2
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,I2C_STOP1
	CALL	I2CEZ80_RESET
I2C_STOP2:
	POP	HL
	XOR	A
	RET
;
;-----------------------------------------------------------------------------
; PUT ONE BYTE (A). THE CONTROLLER ALWAYS CLOCKS THE ACK BIT TOO.
; RETURN A=RESULT, Z IF ACKED.
;
I2C_PUTBYTE:
I2C_PUTBYTE_PIN:
I2C_PUTBYTE_ACK:
	LD	(I2CEZ80_BYTE),A
	CALL	I2CEZ80_ALIVE
	RET	NZ
I2CEZ80_PUT:
	LD	A,(I2CEZ80_BYTE)
	OUT0_A(I2CEZ80_DR)
	LD	A,I2CEZ80_ENAB
	JP	I2CEZ80_STEP		; 18H/20H, 28H/30H, 40H/48H
;
;-----------------------------------------------------------------------------
; EVERY STEP ALREADY WAITED FOR IFLG. RETURN A=RESULT, Z IF OK.
;
I2C_WAIT_FOR_PIN:
I2C_WAIT_FOR_ACK:
	LD	A,(I2CEZ80_RESULT)
	OR	A
	RET
;
;-----------------------------------------------------------------------------
; NO BUS-BUSY BIT ON THIS CONTROLLER, BOTH REPORT FREE
;
I2C_WAIT_FOR_BB:
	XOR	A			; Z, A=0: FREE
	RET
;
I2C_CHECK_BB:
	LD	A,1
	OR	A			; NZ: FREE
	RET
;
;-----------------------------------------------------------------------------
; THE NEXT I2C_GETBYTE NACKS ITS BYTE (LAST BYTE OF A READ)
;
I2C_PREPNACK:
	LD	A,1
	LD	(I2CEZ80_NACKPEND),A
	RET
;
;-----------------------------------------------------------------------------
; RECEIVE ONE BYTE, NACK IT IF I2C_PREPNACK WAS CALLED.
; RETURN A=BYTE, Z. ON FAILURE NZ, A=RESULT.
;
I2C_GETBYTE:
	CALL	I2CEZ80_ALIVE
	RET	NZ
	LD	A,(I2CEZ80_NACKPEND)
	OR	A
	LD	A,I2CEZ80_ENAB | I2CEZ80_AAK
	JR	Z,I2C_GETBYTE1
	XOR	A
	LD	(I2CEZ80_NACKPEND),A
	LD	A,I2CEZ80_ENAB		; AAK=0: NACK THIS BYTE
I2C_GETBYTE1:
	CALL	I2CEZ80_STEP		; 50H/58H
	RET	NZ
	IN0_A(I2CEZ80_DR)
	CP	A			; FORCE Z
	RET
;
I2CEZ80_RESULT:	.DB	I2CEZ80_OK	; RESULT OF THE LAST STEP
I2CEZ80_BYTE:	.DB	0		; BYTE TO SEND, KEPT ACROSS THE START STEP
I2CEZ80_NACKPEND: .DB	0
;
;-----------------------------------------------------------------------------
; INIT-FAILURE PATHS RECORD THE REASON FOR I2CEZ80_INIT TO PRINT LATER.
;
I2C_RECORDFAIL:
	LD	(I2CEZ80_FAIL_MSG),HL	; STASH WHICH MESSAGE APPLIES
	POP	HL			; RESTORE CALLER'S HL
	LD	A,ERR_NOHW
	LD	(I2C_FAIL_FLAG),A
	OR	$FF			; FORCE NZ, THIS IS THE FAILURE PATH
	RET
;
I2CEZ80_NOI2C	.DB	"NOT IDLE AFTER RESET$"
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE TRAILER
;--------------------------------------------------------------------------------------------------
;
END_I2CEZ80	.EQU	$
SIZ_I2CEZ80	.EQU	END_I2CEZ80 - ORG_I2CEZ80
;
	MEMECHO	"I2CEZ80 occupies "
	MEMECHO	SIZ_I2CEZ80
	MEMECHO	" bytes.\n"
