;
;==================================================================================================
; I2CEEPROM - I2C SERIAL EEPROM DIO DRIVER (24LCXXX VIA I2CPCF/I2CBIT)
;==================================================================================================
;
; TREATS THE I2C SERIAL EEPROM AS A RAW BLOCK DEVICE, ONE BLOCK PER
; DIOREAD/DIOWRITE CALL, BLOCK SIZE FIXED AT COMPILE TIME PER UNIT, SHOULD
; MATCH EACH CHIP'S PHYSICAL PAGE SIZE SO WRITES NEVER STRADDLE A PAGE
; BOUNDARY. NOT WIRED TO A CP/M DRIVE LETTER, THESE UNITS NEVER APPEAR IN
; THE BIOS DISK MAP, ONLY REACHABLE BY A PROGRAM CALLING
; BF_DIOSEEK/BF_DIOREAD/BF_DIOWRITE DIRECTLY VIA RST 08.
;
; UP TO 8 FIXED UNITS, ONE PER 24CXX CHIP-SELECT ADDRESS $50-$57
; EACH SLOT IS INDEPENDENTLY ENABLED AND SIZED AT COMPILE TIME
; DISABLED SLOT COSTS NOTHING, ITS CFGTBL ENTRY SIMPLY DOESN'T EXIST
;
; I2CEEPROM_MKADR USES EACH UNIT'S OWN SHIFT TO TURN A BLOCK NUMBER INTO A
; BYTE ADDRESS, REAL 24CXXX PAGE SIZES ARE ALWAYS A POWER OF TWO SO A
; SHIFT COVERS IT.
;
I2CEEPROM_CFGSIZ	.EQU	7	; BYTES PER CFG TABLE ENTRY
					; DEV#
					; BLK# LO
					; BLK# HI
					; I2C ADDR
					; SHIFT
					; BLKCNT LO
					; BLKCNT HI
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE HEADER
;--------------------------------------------------------------------------------------------------
;
ORG_I2CEEPROM	.EQU	$
;
	.DW	SIZ_I2CEEPROM		; MODULE SIZE
	.DW	I2CEEPROM_INITPHASE	; ADR OF INIT PHASE HANDLER
;
I2CEEPROM_INITPHASE:
	; INIT PHASE HANDLER, A=PHASE
	CP	HB_PHASE_INIT		; INIT PHASE?
	JP	Z,I2CEEPROM_INIT		; DO INIT
	RET				; DONE
;
; PER-UNIT CONFIG/STATE, ONE 7-BYTE ENTRY PER ENABLED SLOT, TERMINATED BY
; A LONE $FF, DEV# (BYTE 0) CAN NEVER LEGITIMATELY BE $FF
;
I2CEEPROM_CFGTBL:
#IF (I2CEEPROMADR0ENABLE)
	.DB	0			; DEVICE NUMBER (SET DURING INIT)
	.DW	0			; CURRENT BLOCK NUMBER (SET BY SEEK)
	.DB	$50			; I2C ADDRESS FOR THIS UNIT
	.DB	I2CEEPROMSHIFT0		; SHIFT COUNT, BLKSIZ = 2^SHIFT
	.DW	I2CEEPROMBLKCNT0	; BLOCK COUNT
	DEVECHO	"I2CEEPROM: SLOT 0, ADR=$50\n"
#IF (I2CEEPROMSHIFT0 > 7)
	.ECHO	"*** I2CEEPROM SLOT 0: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR1ENABLE)
	.DB	0
	.DW	0
	.DB	$51
	.DB	I2CEEPROMSHIFT1
	.DW	I2CEEPROMBLKCNT1
	DEVECHO	"I2CEEPROM: SLOT 1, ADR=$51\n"
#IF (I2CEEPROMSHIFT1 > 7)
	.ECHO	"*** I2CEEPROM SLOT 1: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR2ENABLE)
	.DB	0
	.DW	0
	.DB	$52
	.DB	I2CEEPROMSHIFT2
	.DW	I2CEEPROMBLKCNT2
	DEVECHO	"I2CEEPROM: SLOT 2, ADR=$52\n"
#IF (I2CEEPROMSHIFT2 > 7)
	.ECHO	"*** I2CEEPROM SLOT 2: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR3ENABLE)
	.DB	0
	.DW	0
	.DB	$53
	.DB	I2CEEPROMSHIFT3
	.DW	I2CEEPROMBLKCNT3
	DEVECHO	"I2CEEPROM: SLOT 3, ADR=$53\n"
#IF (I2CEEPROMSHIFT3 > 7)
	.ECHO	"*** I2CEEPROM SLOT 3: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR4ENABLE)
	.DB	0
	.DW	0
	.DB	$54
	.DB	I2CEEPROMSHIFT4
	.DW	I2CEEPROMBLKCNT4
	DEVECHO	"I2CEEPROM: SLOT 4, ADR=$54\n"
#IF (I2CEEPROMSHIFT4 > 7)
	.ECHO	"*** I2CEEPROM SLOT 4: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR5ENABLE)
	.DB	0
	.DW	0
	.DB	$55
	.DB	I2CEEPROMSHIFT5
	.DW	I2CEEPROMBLKCNT5
	DEVECHO	"I2CEEPROM: SLOT 5, ADR=$55\n"
#IF (I2CEEPROMSHIFT5 > 7)
	.ECHO	"*** I2CEEPROM SLOT 5: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR6ENABLE)
	.DB	0
	.DW	0
	.DB	$56
	.DB	I2CEEPROMSHIFT6
	.DW	I2CEEPROMBLKCNT6
	DEVECHO	"I2CEEPROM: SLOT 6, ADR=$56\n"
#IF (I2CEEPROMSHIFT6 > 7)
	.ECHO	"*** I2CEEPROM SLOT 6: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
#IF (I2CEEPROMADR7ENABLE)
	.DB	0
	.DW	0
	.DB	$57
	.DB	I2CEEPROMSHIFT7
	.DW	I2CEEPROMBLKCNT7
	DEVECHO	"I2CEEPROM: SLOT 7, ADR=$57\n"
#IF (I2CEEPROMSHIFT7 > 7)
	.ECHO	"*** I2CEEPROM SLOT 7: SHIFT EXCEEDS 7 (128-BYTE STAGEBUF) ***\n"
	!!!
#ENDIF
#ENDIF
	.DB	$FF			; END OF TABLE MARKER
;
I2CEEPROM_DEVNUM:
	.DB	0			; NEXT DEVICE NUMBER TO ASSIGN, WORKING VAR
;
I2CEEPROM_INIT:
	XOR	A
	LD	(I2CEEPROM_DEVNUM),A
	LD	IY,I2CEEPROM_CFGTBL	; IY := START OF CFG TABLE
I2CEEPROM_INIT1:
	LD	A,(IY+0)		; LOAD FIRST BYTE TO CHECK FOR END
	CP	$FF			; CHECK FOR END OF TABLE VALUE
	JP	Z,I2CEEPROM_INIT4	; END OF TABLE, DONE
;
	LD	A,(I2CEEPROM_DEVNUM)	; ASSIGN THIS UNIT'S DEVICE NUMBER
	LD	(IY+0),A
	INC	A
	LD	(I2CEEPROM_DEVNUM),A
;
	CALL	NEWLINE			; FORMATTING
	PRTS("I2CEEPROM: I2C ADDR=0x$")
	LD	A,(IY+3)
	CALL	PRTHEXBYTE
	PRTS(" BLKSIZ=$")
	LD	B,(IY+4)
	CALL	I2CEEPROM_SHIFTTOBYTE	; A := 1 << SHIFT (MOD 256)
	CALL	PRTDECB
	PRTS(" BLKCNT=$")
	LD	L,(IY+5)
	LD	H,(IY+6)
	LD	DE,0
	CALL	PRTDEC
	CALL	PC_SPACE
	LD	A,(IY+3)
	CALL	I2CEEPROM_PROBEADR
	JR	NZ,I2CEEPROM_INIT2
	PRTS("PRESENT$")
	JR	I2CEEPROM_INIT3
I2CEEPROM_INIT2:
	PRTS("NOT FOUND$")
	JR	I2CEEPROM_INIT3B	; ABSENT, SKIP DIO_ADDENT, DON'T REGISTER A PHANTOM UNIT
I2CEEPROM_INIT3:
	PUSH	IY
	POP	DE			; DE := THIS UNIT'S CFG PTR
	LD	BC,I2CEEPROM_FNTBL	; BC := DRIVER FUNC TABLE ADDRESS
	CALL	DIO_ADDENT		; ADD ENTRY TO GLOBAL DISK TABLE
I2CEEPROM_INIT3B:
;
	LD	DE,I2CEEPROM_CFGSIZ
	ADD	IY,DE			; ADVANCE TO NEXT CFG SLOT
	JP	I2CEEPROM_INIT1
I2CEEPROM_INIT4:
	XOR	A			; SIGNAL SUCCESS
	RET
;
; PROBE FOR A CHIP AT THE GIVEN I2C ADDRESS, JUST CHECKS FOR AN I2C ACK
; RETURNS Z=PRESENT, NZ=ABSENT/BUS ERROR
;
I2CEEPROM_PROBEADR:
	LD	B,A
	CALL	I2C_WAIT_FOR_BB
	RET	NZ			; BUS BUSY/TIMEOUT, TREAT AS ABSENT
	LD	A,B
	SLA	A			; WRITE-MODE I2C ADDRESS (R/W BIT=0)
	CALL	I2C_START_ADDR
	CALL	I2C_WAIT_FOR_ACK
	PUSH	AF
	CALL	I2C_STOP
	POP	AF
	RET
;
; RETURN THIS UNIT'S WRITE-MODE / READ-MODE I2C ADDRESS IN A
;
I2CEEPROM_UNIT_WADR:
	LD	A,(IY+3)
	SLA	A			; R/W BIT = 0
	RET
I2CEEPROM_UNIT_RADR:
	LD	A,(IY+3)
	SLA	A
	OR	1			; R/W BIT = 1
	RET
;
; DRIVER FUNCTION TABLE
;
I2CEEPROM_FNTBL:
	.DW	I2CEEPROM_STATUS
	.DW	I2CEEPROM_RESET
	.DW	I2CEEPROM_SEEK
	.DW	I2CEEPROM_READ
	.DW	I2CEEPROM_WRITE
	.DW	I2CEEPROM_VERIFY
	.DW	I2CEEPROM_FORMAT
	.DW	I2CEEPROM_DEVICE
	.DW	I2CEEPROM_MEDIA
	.DW	I2CEEPROM_DEFMED
	.DW	I2CEEPROM_CAP
	.DW	I2CEEPROM_GEOM
#IF (($ - I2CEEPROM_FNTBL) != (DIO_FNCNT * 2))
	.ECHO	"*** INVALID I2CEEPROM FUNCTION TABLE ***\n"
#ENDIF
;
; NOT MEANINGFUL FOR THIS DEVICE, FIXED, NEVER BDOS-MOUNTED
;
I2CEEPROM_VERIFY:
I2CEEPROM_FORMAT:
I2CEEPROM_DEFMED:
I2CEEPROM_GEOM:
	SYSCHKERR(ERR_NOTIMPL)
	RET
;
; CHIP IS ALWAYS PRESENT/READY, NOTHING TO RESET
;
I2CEEPROM_STATUS:
I2CEEPROM_RESET:
	XOR	A
	RET
;
I2CEEPROM_DEVICE:
	LD	D,DIODEV_I2CEEPROM	; D := DEVICE TYPE
	LD	E,(IY+0)		; E := PHYSICAL DEVICE NUMBER
	LD	C,%00011101		; C := ATTRIBUTES, BIT 4=LBA CAPABLE, BITS 3-0=13 (EEPROM,
					; ITS OWN TYPE CODE, SEE PS_DTEE IN INVNTDEV.ASM)
	LD	H,0			; H := 0, DRIVER HAS NO MODES
	LD	L,(IY+3)		; L := THIS UNIT'S I2C ADDRESS
	XOR	A
	RET
;
I2CEEPROM_MEDIA:
	LD	E,MID_NONE		; NOT "ONLINE" MEDIA
	LD	D,0			; D:0=0 MEANS NO MEDIA CHANGE
	LD	A,ERR_NOMEDIA		; NO MEDIA ERROR, KEEPS CBIOS FROM
					; AUTO ASSIGNING THIS A CP/M DRIVE LETTER
	OR	A
	RET
;
; RETURN DE:HL=BLOCK COUNT, BC=BLOCK SIZE, PER THIS UNIT'S OWN CONFIG.
;
I2CEEPROM_CAP:
	LD	DE,0
	LD	L,(IY+5)		; BLOCK COUNT LO
	LD	H,(IY+6)		; BLOCK COUNT HI
	LD	B,(IY+4)		; SHIFT COUNT
	CALL	I2CEEPROM_SHIFTTOBYTE	; A := 1 << B (MOD 256)
	LD	C,A
	LD	B,0
	OR	A
	JR	NZ,I2CEEPROM_CAP1
	INC	B
I2CEEPROM_CAP1:
	XOR	A
	RET
;
; ENTRY: HL = BLOCK NUMBER (0 TO THIS UNIT'S BLKCNT-1)
;
I2CEEPROM_SEEK:
	LD	(IY+1),L
	LD	(IY+2),H
	XOR	A
	RET
;
;--------------------------------------------------------------------------------------------------
; COMPUTE I2C BYTE ADDRESS FOR CURRENT BLOCK (BLOCK# << THIS UNIT'S SHIFT)
; RETURNS BIG-ENDIAN BYTES IN I2CEEPROM_ADRBUF (AS THE 24LCXXX EXPECTS)
;--------------------------------------------------------------------------------------------------
;
I2CEEPROM_MKADR:
	LD	L,(IY+1)		; CURRENT BLOCK NUMBER
	LD	H,(IY+2)
	LD	B,(IY+4)		; THIS UNIT'S SHIFT COUNT
I2CEEPROM_MKADR1:
	LD	A,B
	OR	A
	JR	Z,I2CEEPROM_MKADR2
	ADD	HL,HL
	DEC	B
	JR	I2CEEPROM_MKADR1
I2CEEPROM_MKADR2:
	LD	A,H
	LD	(I2CEEPROM_ADRBUF+0),A	; ADDRESS HIGH BYTE
	LD	A,L
	LD	(I2CEEPROM_ADRBUF+1),A	; ADDRESS LOW BYTE
	RET
;
; A := 1 << B (SHIFT COUNT IN B)
;
I2CEEPROM_SHIFTTOBYTE:
	PUSH	HL
	LD	HL,1
I2CEEPROM_STB1:
	LD	A,B
	OR	A
	JR	Z,I2CEEPROM_STB2
	ADD	HL,HL
	DEC	B
	JR	I2CEEPROM_STB1
I2CEEPROM_STB2:
	LD	A,L
	POP	HL
	RET
;
;--------------------------------------------------------------------------------------------------
; ISSUE START + WRITE-MODE ADDRESS, THEN SEND THE 2-BYTE MEMORY POINTER.
; LEAVES THE BUS IN WRITE MODE, READY FOR EITHER DATA BYTES (WRITE) OR A
; REPEATED START INTO READ MODE.
; RETURNS Z=OK, NZ=ERROR
;--------------------------------------------------------------------------------------------------
;
I2CEEPROM_SETPTR:
	CALL	I2CEEPROM_MKADR
;
	CALL	I2C_WAIT_FOR_BB		; ENSURE BUS FREE
	RET	NZ
;
	CALL	I2CEEPROM_UNIT_WADR
	CALL	I2C_START_ADDR		; SEND ADDR+START (WRITE MODE)
	CALL	I2C_WAIT_FOR_ACK
	RET	NZ
;
	LD	A,(I2CEEPROM_ADRBUF+0)	; MEMORY ADDRESS HIGH BYTE
	CALL	I2C_PUTBYTE_ACK
	RET	NZ
;
	LD	A,(I2CEEPROM_ADRBUF+1)	; MEMORY ADDRESS LOW BYTE
	CALL	I2C_PUTBYTE_ACK
	RET	NZ
;
	XOR	A
	RET
;
;--------------------------------------------------------------------------------------------------
; ENTRY: HL = BUFFER ADDRESS
;--------------------------------------------------------------------------------------------------
;
I2CEEPROM_READ:
	; STASH CALLER'S BUFFER ADDR/BANK
	LD	(I2CEEPROM_CALLERBUF),HL
	LD	A,D
	LD	(I2CEEPROM_CALLERBNK),A
	CALL	I2CEEPROM_SETPTR	; SET MEMORY POINTER (WRITE MODE)
	JP	NZ,I2CEEPROM_READ_ERR2
;
	CALL	I2C_REPSTART		; ISSUE REPEATED START
	CALL	I2CEEPROM_UNIT_RADR
	CALL	I2C_PUTBYTE		; LOAD READ-MODE ADDRESS
	CALL	I2C_WAIT_FOR_ACK
	JP	NZ,I2CEEPROM_READ_ERR2
;
	; FIRST DATA PORT READ AFTER ADDRESS ACK IS A DUMMY
	CALL	I2C_WAIT_FOR_ACK
	JP	NZ,I2CEEPROM_READ_ERR2
	CALL	I2C_GETBYTE		; DISCARD DUMMY BYTE
;
	LD	HL,I2CEEPROM_STAGEBUF	; READ INTO OUR STAGING BUFFER
	LD	B,(IY+4)
	CALL	I2CEEPROM_SHIFTTOBYTE
	LD	B,A
I2CEEPROM_READ1:
	LD	A,B
	CP	1			; LAST BYTE?
	JR	NZ,I2CEEPROM_READ2
	PUSH	HL
	CALL	I2C_PREPNACK		; TELL SLAVE THIS IS THE LAST BYTE
	POP	HL
	PUSH	BC
	CALL	I2C_WAIT_FOR_PIN	; NO ACK EXPECTED AFTER A NACK
	POP	BC
	CP	$FF
	JR	Z,I2CEEPROM_READ_ERR2
	JR	I2CEEPROM_READ3
I2CEEPROM_READ2:
	CALL	I2C_WAIT_FOR_ACK
	JR	NZ,I2CEEPROM_READ_ERR2
I2CEEPROM_READ3:
	CALL	I2C_GETBYTE
	LD	(HL),A
	INC	HL
	DJNZ	I2CEEPROM_READ1
;
	CALL	I2C_STOP
;
	; COPY THE STAGING BUFFER TO THE CALLER'S REAL BUFFER/BANK
	LD	A,BID_BIOS		; SOURCE BANK IS US
	LD	(HB_SRCBNK),A
	LD	A,(I2CEEPROM_CALLERBNK)	; DEST BANK IS THE CALLER'S
	LD	(HB_DSTBNK),A
	LD	HL,I2CEEPROM_STAGEBUF
	LD	DE,(I2CEEPROM_CALLERBUF)
	LD	B,(IY+4)
	CALL	I2CEEPROM_SHIFTTOBYTE
	LD	C,A
	LD	B,0
	OR	A
	JR	NZ,I2CEEPROM_READ4
	INC	B
I2CEEPROM_READ4:
	CALL	HBX_BNKCPY
;
	CALL	I2CEEPROM_BUMPBLK
	XOR	A
	RET
;
I2CEEPROM_READ_ERR2:
	PUSH	AF
	CALL	I2C_STOP
	POP	AF
	LD	A,ERR_IO
	OR	A
	RET
;
;--------------------------------------------------------------------------------------------------
; ENTRY: HL = BUFFER ADDRESS
;--------------------------------------------------------------------------------------------------
;
I2CEEPROM_WRITE:
	; COPY THE CALLER'S REAL BUFFER INTO OUR OWN STAGING BUFFER
	LD	A,D			; CALLER'S BUFFER BANK
	LD	(HB_SRCBNK),A
	LD	A,BID_BIOS
	LD	(HB_DSTBNK),A
	LD	DE,I2CEEPROM_STAGEBUF
	LD	B,(IY+4)
	CALL	I2CEEPROM_SHIFTTOBYTE
	LD	C,A
	LD	B,0
	OR	A
	JR	NZ,I2CEEPROM_WRITE0
	INC	B
I2CEEPROM_WRITE0:
	CALL	HBX_BNKCPY		; HL (CALLER BUF) -> DE (STAGEBUF)
;
	CALL	I2CEEPROM_SETPTR	; SET MEMORY POINTER (WRITE MODE)
	JR	NZ,I2CEEPROM_WRITE_ERR2
;
	LD	HL,I2CEEPROM_STAGEBUF	; WRITE FROM OUR STAGING BUFFER
	LD	B,(IY+4)
	CALL	I2CEEPROM_SHIFTTOBYTE
	LD	B,A
I2CEEPROM_WRITE1:
	LD	A,(HL)
	PUSH	HL
	PUSH	BC
	CALL	I2C_PUTBYTE_ACK
	POP	BC
	POP	HL
	JR	NZ,I2CEEPROM_WRITE_ERR2
	INC	HL
	DJNZ	I2CEEPROM_WRITE1
;
	CALL	I2C_STOP
	CALL	I2CEEPROM_WRITE_WAIT	; WAIT FOR THE CHIP'S WRITE CYCLE
	RET	NZ
;
	CALL	I2CEEPROM_BUMPBLK
	XOR	A
	RET
;
I2CEEPROM_WRITE_ERR2:
	PUSH	AF
	CALL	I2C_STOP
	POP	AF
	LD	A,ERR_IO
	OR	A
	RET
;
; WHILE THE CHIP IS COMMITTING A PAGE WRITE, IT NAKS ANY NEW START
; POLL UNTIL IT ACKS OR WE GIVE UP
;
I2CEEPROM_WRITE_WAIT:
	LD	B,0			; TRY 256 TIMES
I2CEEPROM_WRITE_WAIT1:
	PUSH	BC
	CALL	I2CEEPROM_UNIT_WADR
	CALL	I2C_START_ADDR
	CALL	I2C_WAIT_FOR_ACK
	PUSH	AF
	CALL	I2C_STOP
	POP	AF
	POP	BC
	JR	Z,I2CEEPROM_WRITE_WAIT2	; ACKED, CHIP IS READY
	DJNZ	I2CEEPROM_WRITE_WAIT1
	LD	A,ERR_IO		; GAVE UP
	OR	A
	RET
I2CEEPROM_WRITE_WAIT2:
	XOR	A
	RET
;
; ADVANCE TO THE NEXT BLOCK
;
I2CEEPROM_BUMPBLK:
	LD	L,(IY+1)
	LD	H,(IY+2)
	INC	HL
	LD	(IY+1),L
	LD	(IY+2),H
	RET
;
I2CEEPROM_ADRBUF:
	.FILL	2,0			; MEMORY ADDRESS BUFFER
;
; BANK SUPPORT: HBX_INVOKE SWITCHES TO THE BIOS BANK BEFORE CALLING
; ANY DRIVER, SO I2CEEPROM_READ/WRITE MUST NOT TOUCH THE CALLER'S BUFFER
; ADDRESS DIRECTLY, THEY STAGE THROUGH THIS BUFFER AND COPY VIA
; HBX_BNKCPY INSTEAD.
;
I2CEEPROM_STAGEBUF:
	.FILL	128,0			; STAGING BUFFER, BIOS BANK. SIZED FOR
					; SHIFT=7 (BLKSIZ=128), THE LARGEST
					; SHIFT THE CFGTBL !!! GUARD ALLOWS
I2CEEPROM_CALLERBUF:
	.DW	0			; CALLER'S REAL BUFFER ADDRESS (READ ONLY)
I2CEEPROM_CALLERBNK:
	.DB	0			; CALLER'S REAL BUFFER BANK (READ ONLY)
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE TRAILER
;--------------------------------------------------------------------------------------------------
;
END_I2CEEPROM	.EQU	$
SIZ_I2CEEPROM	.EQU	END_I2CEEPROM - ORG_I2CEEPROM
;
	MEMECHO	"I2CEEPROM occupies "
	MEMECHO	SIZ_I2CEEPROM
	MEMECHO	" bytes.\n"
