;
;==================================================================================================
; HARDWARE SUPPORT FOR HITACHI HD44780 OR EQUIVALENT VIA PCF8574 I2C BACKPACK
;==================================================================================================
;
; CURRENTLY ASSUMES A 20X4 DISPLAY
;
; ALTERNATE TO lcd.asm (PARALLEL BUS)
; ONLY ONE OF LCDENABLE/LCDI2CENABLE MAY BE TRUE
; SAME LCD_* LABELS AS lcd.asm, THEY CAN NEVER BE ASSEMBLED TOGETHER
;
; REQUIRES i2cpcf.asm (I2CPCFENABLE) OR i2cbit.asm (I2CBITENABLE) FOR THE
; UNDERLYING I2C BUS MASTER
;
; PCF8574 BACKPACK IS CURRENTLY USED IN WRITE-ONLY MODE
; FUTURE PLANS MAY CHANGE THAT
; NO BUSY FLAG, NO DDRAM READBACK
; THE DRIVER USES I2C-ACK PRESENCE DETECTION INSTEAD
;
#IF (LCDENABLE & LCDI2CENABLE)
	.ECHO	"*** ERROR: LCDENABLE AND LCDI2CENABLE CANNOT BOTH BE TRUE -- CHOOSE ONE!!!\n"
	!!!	; FORCE AN ASSEMBLY ERROR
#ENDIF
;
#IF (LCDI2CENABLE & !(I2CPCFENABLE | I2CBITENABLE))
	.ECHO	"*** ERROR: LCDI2CENABLE REQUIRES PCFENABLE OR I2CBITENABLE!!!\n"
	!!!	; FORCE AN ASSEMBLY ERROR
#ENDIF
;
LCD_ROWS	.EQU	4
LCD_COLS	.EQU	20
;
; PCF8574 BACKPACK PIN MAP (COMMON 4-BIT LCD BACKPACK WIRING)
;
LCD_I2C_RS	.EQU	00000001B	; P0: REGISTER SELECT (0=CMD, 1=DATA)
LCD_I2C_RW	.EQU	00000010B	; P1: 0=WRITE, 1=READ
LCD_I2C_EN	.EQU	00000100B	; P2: ENABLE STROBE
LCD_I2C_BL	.EQU	00001000B	; P3: BACKLIGHT (ON)
;
LCD_FUNC_CLEAR	.EQU	$01		; CLEAR DISPLAY
LCD_FUNC_HOME	.EQU	$02		; HOME CURSOR & REMOVE ALL SHIFTING
LCD_FUNC_ENTRY	.EQU	$04		; SET CUR DIR AND DISPLAY SHIFT
LCD_FUNC_DISP	.EQU	$08		; DISP, CUR, BLINK ON/OFF
LCD_FUNC_SHIFT	.EQU	$10		; MOVE CUR / SHIFT DISP
LCD_FUNC_SET	.EQU	$20		; SET INTERFACE PARAMS
LCD_FUNC_CGADR	.EQU	$40		; SET CGRAM ADRESS
LCD_FUNC_DDADR	.EQU	$80		; SET DDRAM ADDRESS
;
	DEVECHO	"LCD: I2C ADDR="
	DEVECHO	LCDI2CADDR
	DEVECHO	", SIZE="
	DEVECHO	LCD_COLS
	DEVECHO	"X"
	DEVECHO	LCD_ROWS
	DEVECHO	"\n"
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE HEADER
;--------------------------------------------------------------------------------------------------
;
ORG_LCD	.EQU	$
;
	.DW	SIZ_LCD		; MODULE SIZE
	.DW	LCD_INITPHASE		; ADR OF INIT PHASE HANDLER
;
LCD_INITPHASE:
	; INIT PHASE HANDLER, A=PHASE
	CP	HB_PHASE_PREINIT	; PREINIT PHASE?
	JP	Z,LCD_PREINIT		; DO PREINIT
	CP	HB_PHASE_INIT		; INIT PHASE?
	JP	Z,LCD_INIT		; DO FULL BRING-UP + DIAGNOSTIC PRINT
	RET				; DONE
;
; PREINIT: NOTHING TO DO
;
LCD_PREINIT:
	RET
;
; FULL HARDWARE BRING-UP, RUNS AFTER I2C_INIT
;
LCD_INIT:
	CALL	NEWLINE			; FORMATTING
	PRTS("LCD: $")
;
	PRTS("I2C ADDR=0x$")
	LD	A,LCDI2CADDR
	CALL	PRTHEXBYTE
;
	; CHECK IF I2C INITIALISATION FAILED
	LD	A,(I2C_FAIL_FLAG)
	OR	A
	JP	NZ,LCD_INIT_NOI2C
;
	CALL	LCD_DETECT		; PROBE FOR HARDWARE VIA I2C ACK
	LD	A,(LCD_PRESENT)		; GET PRESENCE FLAG
	OR	A			; SET FLAGS
	JP	Z,LCD_INIT_NOLCD	; HANDLE NOT PRESENT
;
	; ENTIRE BRING-UP IS ONE CONTINUOUS I2C TRANSACTION
	;
	CALL	I2C_WAIT_FOR_BB
	JR	Z,LCD_INIT_GO
	RET				; BUS STUCK BUSY, GIVE UP QUIETLY
LCD_INIT_GO:
	CALL	LCD_BUSSTART
	JR	NZ,LCD_INIT_STOP	; NO ACK, BAIL
;
	; HD44780 4-BIT WAKE-UP SEQUENCE (SEE DATASHEET), THEN NORMAL INIT
	CALL	LCD_RESETSEQ
	LD	DE,LCD_INIT_SEQ		; INIT SEQUENCE
	CALL	LCD_OUTFS		; SEND IT
;
	; PUT SOMETHING ON THE DISPLAY
	LD	DE,LCD_STR_BAN
	CALL	LCD_OUTDS
;
	; SECOND LINE
	; CPU TYPE
	LD	HL,$0100		; ROW 2, COL 0
	CALL	LCD_GOTORC
	LD	HL,LCD_CPU
	LD	A,(HB_CPUTYPE)		; GET CPU TYPE
	RLCA				; WORD OFFSET
	CALL	ADDHLA			; ADD OFFSET
	LD	E,(HL)			; GET LSB
	INC	HL			; BUMP
	LD	D,(HL)			; GET MSB
	CALL	LCD_OUTDS
	LD	DE,LCD_STR_XPU
	CALL	LCD_OUTDS
;
	CALL	LCD_EVT_CPUSPD
;
	; THIRD LINE
	LD	HL,$0200		; ROW 2, COL 0
	CALL	LCD_GOTORC
	LD	DE,LCD_STR_CFG
	CALL	LCD_OUTDS
;
	; REGISTER DRIVER WITH HBIOS, ONLY NOW THAT BRING-UP FINISHED
	LD	BC,LCD_DISPATCH
	CALL	DSKY_SETDISP
;
LCD_INIT_STOP:
	CALL	I2C_STOP
	XOR	A			; SIGNAL SUCCESS
	RET				; DONE
;
; LCD WAS NOT FOUND ON THE I2C BUS
;
LCD_INIT_NOLCD:
	PRTS(" NOT PRESENT$")
	OR	$FF
	RET
;
; I2C NEVER CAME UP
;
LCD_INIT_NOI2C:
	PRTS(" I2C FAILURE$")
	OR	$FF
	RET
;
; DSKY DEVICE FUNCTION DISPATCH ENTRY
;   A: RESULT (OUT), 0=OK, Z=OK, NZ=ERR
;   B: FUNCTION (IN)
;
LCD_DISPATCH:
	LD	A,B			; GET REQUESTED FUNCTION
	AND	$0F			; ISOLATE SUB-FUNCTION
	JP	Z,LCD_NULL		; RESET DSKY HARDWARE
	DEC	A
	JP	Z,LCD_NULL		; GET KEYPAD STATUS
	DEC	A
	JP	Z,LCD_NULL		; READ A KEY FROM THE KEYPAD
	DEC	A
	JP	Z,LCD_NULL		; DISPLAY A 32-BIT BINARY VALUE IN HEX
	DEC	A
	JP	Z,LCD_SHOWSEG		; DISPLAY SEGMENTS
	DEC	A
	JP	Z,LCD_NULL		; SET KEYPAD LEDS
	DEC	A
	JP	Z,LCD_NULL		; SET STATUS LED
	DEC	A
	JP	Z,LCD_NULL		; BEEP DSKY SPEAKER
	DEC	A
	JP	Z,LCD_DEVICE		; DEVICE INFO
	DEC	A
	JP	Z,LCD_MESSAGE		; HANDLE MESSAGE
	DEC	A
	JP	Z,LCD_EVENT		; HANDLE EVENT
	SYSCHKERR(ERR_NOFUNC)
	RET
;
LCD_NULL:
	XOR	A
	RET
;
; DRAW DISPLAY USING DEBUG ALPHABET
; HL = SOURCE BUFFER
;
LCD_SHOWSEG:
	XOR	A
	RET
;
; DEVICE INFORMATION
;
LCD_DEVICE:
	LD	D,DSKYDEV_LCD		; D := DEVICE TYPE
	LD	E,0			; E := PHYSICAL DEVICE NUMBER
	LD	H,0			; H := MODE
	LD	L,LCDI2CADDR		; L := I2C ADDRESS
	XOR	A			; SIGNAL SUCCESS
	RET
;
; MESSAGE HANDLER
;
LCD_MESSAGE:
	LD	A,C			; GET MESSAGE ID
	ADD	A,A			; WORD OFFSET
	LD	HL,LCD_MSGTBL		; START OF MESSAGE TABLE
	CALL	ADDHLA			; ADD OFFSET
	LD	A,(HL)			; SAVE LSB
	INC	HL			; BUMP TO MSB
	LD	H,(HL)			; GET MSB
	LD	L,A			; GET LSB
;
	EX	DE,HL
	CALL	I2C_WAIT_FOR_BB
	JR	Z,LCD_MESSAGE_GO
	XOR	A			; BUS STUCK BUSY, FORCE SUCCESS
	RET
LCD_MESSAGE_GO:
	CALL	LCD_BUSSTART
	JR	NZ,LCD_MESSAGE_STOP	; NO ACK, BAIL
	LD	HL,$0300		; ROW 3, COL 0
	CALL	LCD_GOTORC
	JR	NZ,LCD_MESSAGE_STOP
	CALL	LCD_LINEOUT
LCD_MESSAGE_STOP:
	CALL	I2C_STOP
	XOR	A			; SIGNAL SUCCESS
	RET
;
; EVENT HANDLER
;
LCD_EVENT:
	LD	A,C			; EVENT ID
	OR	A			; 0=CPUSPD
	JR	Z,LCD_EVT_CPUSPD_I2C	; HANDLE CPU SPD CHANGE
	DEC	A			; 1=DSKACT
	JR	Z,LCD_EVT_DSKACT	; HANDLE DISK ACTIVITY
	XOR	A
	RET
;
; CPU SPEED CHANGE, WRAPPED IN ITS OWN I2C TRANSACTION FOR POST-BOOT EVENT
;
LCD_EVT_CPUSPD_I2C:
	CALL	I2C_WAIT_FOR_BB
	JR	Z,LCD_EVT_CPUSPD_I2C_GO
	RET				; BUS STUCK BUSY, GIVE UP QUIETLY
LCD_EVT_CPUSPD_I2C_GO:
	CALL	LCD_BUSSTART
	JR	NZ,LCD_EVT_CPUSPD_I2C_STOP	; NO ACK, BAIL
	CALL	LCD_EVT_CPUSPD
LCD_EVT_CPUSPD_I2C_STOP:
	CALL	I2C_STOP
	RET
;
LCD_EVT_CPUSPD:
	; "12.345 MHz" RIGHT JUSTIFIED
	LD	HL,$010A		; ROW 2, COL 10
	CALL	LCD_GOTORC
	RET	NZ			; NO ACK, BAIL
	LD	HL,(CB_CPUKHZ)
	PUSH	HL
	LD	BC,10000		; 10 MHZ
	SBC	HL,BC			; SUBTRACT
	JR	NC,LCD_EVT_CPUSPD1
	LD	A,' '			; EXTRA PAD
	CALL	LCD_OUTD
LCD_EVT_CPUSPD1:
	POP	HL
	CALL	LCD_PRTD3M		; PRINT AS DECIMAL WITH 3 DIGIT MANTISSA
	LD	DE,LCD_STR_MHZ
	CALL	LCD_OUTDS
	RET
;
; FORMAT: "Disk #99  R:12345678"
;          01234567890123456789
;
LCD_EVT_DSKACT:
	CALL	I2C_WAIT_FOR_BB
	JR	Z,LCD_EVT_DSKACT_GO
	RET				; BUS STUCK BUSY, GIVE UP QUIETLY
LCD_EVT_DSKACT_GO:
	CALL	LCD_BUSSTART
	JR	NZ,LCD_EVT_DSKACT_STOP	; NO ACK, BAIL
	LD	HL,$0300		; ROW 3, COL 0
	CALL	LCD_GOTORC		; SET DISPLAY ADDRESS
	JR	NZ,LCD_EVT_DSKACT_STOP
;
	LD	DE,LCD_STR_IO		; PREFIX
	CALL	LCD_OUTDS		; SEND TO DISPLAY (COLS 0-5)
;
	LD	A,(HB_DSKUNIT)		; GET DISK UNIT NUM
	CALL	LCD_EVT_DSKACT_BYTE	; SEND TO DISPLAY (COLS 6-7)
;
	LD	A,' '			; SEPARATOR
	CALL	LCD_OUTD		; SEND TO DISPLAY (COL 8)
	CALL	LCD_OUTD		; SEND TO DISPLAY (COL 9)
;
	LD	A,(HB_DSKFUNC)		; ACTIVE DISK FUNCTION
	CP	BF_DIOWRITE		; WRITE?
	LD	A,'W'			; ASSUME WRITE
	JR	Z,LCD_EVT_DSKACT0	; GO AHEAD
	LD	A,'R'			; OTHERWISE READ
LCD_EVT_DSKACT0:
	CALL	LCD_OUTD		; SEND CHAR (COL 10)
;
	LD	A,':'			; SEPARATOR
	CALL	LCD_OUTD		; SEND TO DISPLAY (COL 11)
;
	LD	HL,HB_DSKADR+3		; END OF DWORD (MSB)
	LD	B,4			; DO 4 BYTES
LCD_EVT_DSKACT1:
	LD	A,(HL)			; GET BYTE
	CALL	LCD_EVT_DSKACT_BYTE	; SEND TO DISPLAY (COLS 12-19)
	DEC	HL			; DEC PTR
	DJNZ	LCD_EVT_DSKACT1		; DO ALL 4 BYTES
LCD_EVT_DSKACT_STOP:
	CALL	I2C_STOP
	RET
;
LCD_EVT_DSKACT_BYTE:
	PUSH	AF			; SAVE BYTE
	RRCA				; DO TOP NIBBLE FIRST
	RRCA
	RRCA
	RRCA
	CALL	HEXCONV			; CONVERT NIBBLE TO ASCII
	CALL	LCD_OUTD		; SEND TO DISPLAY
	POP	AF			; RECOVER CURRENT BYTE
	CALL	HEXCONV			; CONVERT NIBBLE TO ASCII
	CALL	LCD_OUTD		; SEND TO DISPLAY
	RET				; DONE
;
; DETECT PRESENCE OF LCD CONTROLLER VIA I2C ACK.
;
LCD_DETECT:
	CALL	I2C_WAIT_FOR_BB
	JR	NZ,LCD_DETECT1		; BUS BUSY, ASSUME NOT PRESENT
;
	LD	A,LCDI2CADDR << 1	; SLAVE ADDRESS (WRITE)
	CALL	I2C_START_ADDR		; GENERATE START CONDITION
	CALL	I2C_WAIT_FOR_ACK	; DID IT ACK?
	PUSH	AF			; SAVE RESULT
	CALL	I2C_STOP		; RELEASE BUS EITHER WAY
	POP	AF
	JR	NZ,LCD_DETECT1
;
	; LCD PRESENT
	OR	$FF
	JR	LCD_DETECT_Z
;
LCD_DETECT1:
	; LCD NOT PRESENT
	XOR	A
;
LCD_DETECT_Z:
	LD	(LCD_PRESENT),A
	RET
;
; ISSUE SLAVE ADDRESS + START
; CALLER MUST HAVE ALREADY CONFIRMED I2C_WAIT_FOR_BB SUCCEEDED
; RETURNS Z IF READY TO SEND BYTES, NZ IF NO ACK
; CALLER SHOULD STILL CALL I2C_STOP TO RELEASE THE BUS
;
LCD_BUSSTART:
	LD	A,LCDI2CADDR << 1
	CALL	I2C_START_ADDR
	CALL	I2C_WAIT_FOR_ACK
	RET
;
; SEND FUNCTION CODE IN A
;
LCD_OUTF:
	PUSH	BC
	LD	C, 0
	JR	LCD_BYTE
;
; SEND FUNCTION STRING AS ONE I2C TRANSACTION
; ASSUMES BUS OPEN
; DE=STRING ADDRESS, NULL TERMINATED
;
LCD_OUTFS:
	LD	A,(DE)			; NEXT BYTE TO SEND
	OR	A			; SET FLAGS
	RET	Z			; DONE WHEN NULL REACHED
	INC	DE			; BUMP POINTER
	PUSH	AF
	CALL	LCD_OUTF		; SEND IT
	JR	NZ,LCD_OUTFS_FAIL	; FAILED, ABORT
	POP	AF
	CP	LCD_FUNC_CLEAR
	JR	NZ,LCD_OUTFS
	;;;; CLEAR DISPLAY NEEDS TIME TO EXECUTE, ~0.5S BLIND DELAY VIA LDELAY.
	;;;CALL	LDELAY
	; CLEAR DISPLAY NEEDS TIME TO EXECUTE, ~0.05S BLIND DELAY
	PUSH	DE
	LD	DE,50000/16		; WAIT >4.1MS, WE USE 50MS
	CALL	VDELAY			; DO IT
	POP	DE
	JR	LCD_OUTFS
LCD_OUTFS_FAIL:
	POP	AF			; CLEANUP
	OR	1			; FORCE NZ
	RET
;
; SEND DATA BYTE IN A
;
LCD_OUTD:
	PUSH	BC
	LD	C, LCD_I2C_RS
;
; SEND FULL BYTE AS TWO NIBBLES
; ASSUMES BUS OPEN
; A=BYTE
; C=REGISTER SELECT (0=CMD, 1=DATA)
; RETURNS Z ON SUCCESS, NZ IF EITHER NIBBLE FAILED
;
LCD_BYTE:
	PUSH	DE
	PUSH	HL
	LD	HL, LCD_BUF
	PUSH	AF
	AND	$F0			; UPPER NIBBLE
	OR	LCD_I2C_EN|LCD_I2C_BL
	OR	C
	LD	(HL), A
	INC	HL
	AND	~LCD_I2C_EN
	LD	(HL), A
	INC	HL
	POP	AF
	PUSH	AF			; SAVE BYTE AGAIN, WE NEED IT LATER
	RLCA
	RLCA
	RLCA
	RLCA
	AND	$F0			; LOWER NIBBLE
	OR	LCD_I2C_EN|LCD_I2C_BL
	OR	C
	LD	(HL), A
	INC	HL
	AND	~LCD_I2C_EN
	LD	(HL), A
	LD	HL, LCD_BUF
	LD	B,4			; REQUIRES A FOUR CYCLE SEND
	CALL	LCD_SENDBUF		; SETS Z/NZ -- MUST SURVIVE TO RET
	POP	DE			; D=SAVED BYTE, E=SAVED FLAGS (DISCARDED)
	LD	A,D			; RESTORE BYTE -- LD DOESN'T TOUCH FLAGS, POP DOESN'T EITHER
	POP	HL
	POP	DE			; RESTORE CALLER'S DE (SAVED ABOVE, LCD_OUTDS KEEPS ITS STRING PTR HERE)
	POP	BC
	RET
;
LCD_NIBBLE_CMD:
	PUSH	BC
	PUSH	HL
	LD	HL, LCD_BUF
	AND	$F0
	OR	LCD_I2C_EN|LCD_I2C_BL
	LD	(HL), A
	INC	HL
	AND	~LCD_I2C_EN
	LD	(HL), A
	LD	HL, LCD_BUF
	LD	B,2		; REQUIRES A TWO CYCLE SEND
	CALL	LCD_SENDBUF
	POP	HL
	POP	BC
	RET
;
LCD_SENDBUF:
	LD	C,0
LCD_SENDBUF1:
	LD	A,(HL)
	CALL	I2C_PUTBYTE_ACK	; PUT DATA ON BUS, WAIT FOR ACK
	JR	Z,LCD_SENDBUF2
	INC	C		; REMEMBER FAILURE
LCD_SENDBUF2:
	INC	HL
	DJNZ	LCD_SENDBUF1
	LD	A,C
	OR	A		; SET Z/NZ FOR CALLER
	RET
;
LCD_BUF:
     .DB   0, 0, 0, 0		; BUFFER TO HOLD 4 BYTE SEQUENCE
;
; SEND STRING, BLANK-PAD TO END OF LINE
; ASSUMES BUS OPEN
; DE=STRING, NULL-TERMINATED, RETURNS Z/NZ
;
LCD_LINEOUT:
	LD	B,LCD_COLS
	CALL	LCD_OUTDS
	RET	NZ			; CONTENT SEND FAILED, SKIP PADDING
LCD_LINEOUT1:
	LD	A,' '
	CALL	LCD_OUTD
	RET	NZ			; FAILED, ABORT PADDING
	DJNZ	LCD_LINEOUT1
	RET
;
; SEND DATA STRING
; ASSUMES BUS OPEN
; DE=STRING ADDRESS, NULL TERMINATED
;
LCD_OUTDS:
	LD	A,(DE)			; NEXT BYTE TO SEND
	OR	A			; SET FLAGS
	RET	Z			; DONE WHEN NULL REACHED
	INC	DE			; BUMP POINTER
	DEC	B			; PADDING COUNTER FOR ABOVE
	CALL	LCD_OUTD		; SEND IT
	RET	NZ			; FAILED, ABORT
	JR	LCD_OUTDS		; LOOP AS NEEDED
;
; HD44780 RESET SEQUENCE (SEE DATASHEET)
; ASSUMES BUS OPEN
;
LCD_RESETSEQ:
	LD	A,$30			; FUNCTION SET, 8-BIT (UPPER NIBBLE ONLY)
	CALL	LCD_NIBBLE_CMD
	LD	A,$30			; SEND 3 TIMES BACK-TO-BACK, NO DELAY BETWEEN
	CALL	LCD_NIBBLE_CMD
	LD	A,$30
	CALL	LCD_NIBBLE_CMD
	;;;CALL	LDELAY			; ONE DELAY AFTER ALL 3 (~500MS)
	LD	DE,5000/16		; WAIT >4.1MS, WE USE 5MS
	CALL	VDELAY			; DO IT
	LD	A,$20			; SWITCH TO 4-BIT MODE
	CALL	LCD_NIBBLE_CMD
	;;;CALL	LDELAY			; ONE DELAY AFTER THE SWITCH (~500MS)
	LD	DE,5000/16		; WAIT >4.1MS, WE USE 5MS
	CALL	VDELAY			; DO IT
	RET
;
; GOTO ROW(H),COL(L)
; ASSUMES BUS OPEN
;
LCD_GOTORC:
	PUSH	HL			; SAVE INCOMING
	LD	A,H			; ROW # TO A
	LD	HL,LCD_ROWSIDX		; POINT TO ROWS INDEX TABLE
	CALL	ADDHLA			; INDEX TO ROW ENTRY
	LD	A,(HL)			; GET RWO START
	POP	HL			; RECOVER INCOMING
	ADD	A,L			; ADD COLUMN
	ADD	A,LCD_FUNC_DDADR	; APPLY FUNCTION BIT
	JP	LCD_OUTF		; AND SEND IT
;
; PRINT VALUE OF HL AS THOUSANDTHS, IE. 0.000
; ASSUMES BUS OPEN
;
LCD_PRTD3M:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	E,'0'
	LD	BC,-10000
	CALL	LCD_PRTD3M1
	LD	E,0
	LD	BC,-1000
	CALL	LCD_PRTD3M1
	LD	A,'.'
	CALL	LCD_OUTD
	LD	BC,-100
	CALL	LCD_PRTD3M1
	LD	C,-10
	CALL	LCD_PRTD3M1
	LD	C,-1
	CALL	LCD_PRTD3M1
	POP	HL
	POP	DE
	POP	BC
	RET
LCD_PRTD3M1:
	LD	A,'0' - 1
LCD_PRTD3M2:
	INC	A
	ADD	HL,BC
	JR	C,LCD_PRTD3M2
	SBC	HL,BC
	CP	E
	JR	Z,LCD_PRTD3M3
	LD	E,0
	CALL	LCD_OUTD
LCD_PRTD3M3:
	RET
;
; DATA STORAGE
;
LCD_PRESENT	.DB	0		; NON-ZERO WHEN HARDWARE DETECTED
;
LCD_ROWSIDX	.DB	$00,$40,$14,$54	; ROW START INDEX
;
LCD_INIT_SEQ:
	.DB	LCD_FUNC_SET | %01000	; FUNCTION SET, 4-BIT, 2 LINES, 5X8 FONT
	.DB	LCD_FUNC_DISP		; DISPLAY OFF
	.DB	LCD_FUNC_CLEAR		; CLEAR DISPLAY, HOME CURSOR
	.DB	LCD_FUNC_ENTRY | $02	; INCREMENT, NO SHIFT
	.DB	LCD_FUNC_DISP | $04	; DISPLAY ON, NO CURSOR, NO BLINK
	.DB	$00			; TERMINATOR
;
LCD_STR_BAN	.DB	"RomWBW v", BIOSVER, 0
LCD_STR_CFG	.DB	CONFIG, 0
LCD_STR_IO	.DB	"Disk #", 0
LCD_STR_XPU	.DB	" CPU",0
LCD_STR_MHZ	.DB	" MHz",0
;
; INDEXED AS PER CPT_xxx
LCD_CPU		.DW	LCD_CPU_Z80
		.DW	LCD_CPU_Z180
		.DW	LCD_CPU_Z180K
		.DW	LCD_CPU_Z180N
		.DW	LCD_CPU_Z280
		.DW	LCD_CPU_EZ80
;
LCD_CPU_Z80	.DB	"Z80",0
LCD_CPU_Z180	.DB	"Z180",0
LCD_CPU_Z180K	.DB	"Z180K",0
LCD_CPU_Z180N	.DB	"Z180N",0
LCD_CPU_Z280	.DB	"Z280",0
LCD_CPU_EZ80	.DB	"eZ80",0
;
LCD_MSGTBL:
	.DW	LCD_MSG_LDR_SEL
	.DW	LCD_MSG_LDR_BOOT
	.DW	LCD_MSG_LDR_LOAD
	.DW	LCD_MSG_LDR_GO
	.DW	LCD_MSG_MON_RDY
	.DW	LCD_MSG_MON_BOOT
;
LCD_MSG_LDR_SEL		.DB	"Ready",0
LCD_MSG_LDR_BOOT	.DB	"Boot...",0
LCD_MSG_LDR_LOAD	.DB	"Load...",0
LCD_MSG_LDR_GO		.DB	"Go...",0
LCD_MSG_MON_RDY		.DB	"-CPU UP-",0
LCD_MSG_MON_BOOT	.DB	"Boot!",0
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE TRAILER
;--------------------------------------------------------------------------------------------------
;
END_LCD	.EQU	$
SIZ_LCD	.EQU	END_LCD - ORG_LCD
;
	MEMECHO	"LCD-I2C occupies "
	MEMECHO	SIZ_LCD
	MEMECHO	" bytes.\n"
