OBJECTS = ZETA2_std.rom
SUBDIRS = 
DEST = ../../Binary/Apps
TOOLS =../../Tools
OTHERS =  *.bin *.z80 cpm.sys zsys.sys Build.inc
include $(TOOLS)/Makefile.inc

ZETA2_std.rom:
	bash Build.sh ZETA2 std 512

