;
; Program: NOTE (Note)
; Author: Richard Conn
; Version: 1.0
; Date: 8 Mar 84
; Previous Versions: None
;

;
;	NOTE is a comment - it does nothing except return
;

;
; Macros and Externals
;
	MACLIB	Z3BASE.LIB
	ext	z3init

;
; Environment Definition
;
	if	z3env ne 0
;
; External ZCPR3 Environment Descriptor
;
	jmp	start
	db	'Z3ENV'	;This is a ZCPR3 Utility
	db	1	;External Environment Descriptor
z3eadr:
	dw	z3env
start:
	lhld	z3eadr	;pt to ZCPR3 environment
;
	else
;
; Internal ZCPR3 Environment Descriptor
;
	MACLIB	SYSENV.LIB
z3eadr:
	jmp	start
	SYSENV
start:
	lxi	h,z3eadr	;pt to ZCPR3 environment
	endif

;
; Start of Program -- Initialize ZCPR3 Environment
;
	jmp	z3init	;initialize the ZCPR3 Env and the VLIB Env

	end
