@echo off
@echo Copy CP/M-80 executables from the crossdev folder to here (core only)
@copy ..\crossdev\ACCESS.CPM ACCESS.COM
@copy ..\crossdev\CPMNAME.CPM CPMNAME.COM
@copy ..\crossdev\FINDFILE.CPM FINDFILE.COM
@copy ..\crossdev\MAP.CPM MAP.COM
@copy ..\crossdev\META.CPM META.COM
@copy ..\crossdev\MULTIFMT.CPM MULTIFMT.COM
@copy ..\crossdev\REM.CPM REM.COM
@copy ..\crossdev\SETLABEL.CPM SETLABEL.COM
@copy ..\crossdev\SYSGEN.CPM SYSGEN.COM
@copy ..\crossdev\TERMTYPE.CPM TERMTYPE.COM
@copy ..\crossdev\VIEW.CPM VIEW.COM
