#
# order is actually important, because of build dependencies
#
NOTDONE = Doc
SUBDIRS = Prop
SUBDIRS += Apps 
SUBDIRS += CBIOS HBIOS 
SUBDIRS += CPM22 ZCPR ZCPR-DJ ZSDOS CPM3
SUBDIRS += ZPM3
SUBDIRS += Forth
NOTDONE += Fonts
SUBDIRS += BPBIOS
SUBDIRS += HBIOS
SUBDIRS += Images
TOOLS = ../Tools
include $(TOOLS)/Makefile.inc
