# Build with: docker build --progress plain -t romwbw-z88dk .
# run with  : docker run -v ${PWD}:/src/ --privileged=true -u $(id -u ${USER}):$(id -g ${USER}) -it romwbw-z88dk:latest

FROM z88dk/z88dk 

RUN apk add build-base
