name: Release Build

on:
  push:
    tags:
      - '**'

jobs:

  # Build new release
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install libncurses-dev
          sudo apt-get install srecord
          make transpile-c-code
          make distlog --trace

      - name: Create Package Archive
        run: |
          zip -r RomWBW-${{github.ref_name}}-Package.zip . --exclude .git\*

      - name: Set Title
        run: |
          echo "Tag: ${{github.ref_name}}"
          if grep -q "dev" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Development Snapshot"
          elif grep -q "beta" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Beta Release"
          elif grep -q "pre" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Prerelease"
          elif grep -q "rc" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Release Candidate"
          else
            TITLE="RomWBW"
          fi
          echo "Title: $TITLE"
          echo "TITLE=$TITLE" >>$GITHUB_ENV

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{github.ref_name}}
        run: |
          gh release create "$TAG" RomWBW-$TAG-Package.zip \
            --draft --prerelease \
            --title="${{env.TITLE}} $TAG" \
            --generate-notes

  # Generate and deploy GitHub pages
  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Docs
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install gpp pandoc
          pip install mkdocs
          make -C Source/Doc deploy_mkdocs
          mkdocs build -f Source/Doc/mkdocs.yml

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'Source/Doc/site'

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
