name: Release Build

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install libncurses-dev
          sudo apt-get install srecord
          make transpile-c-code
          make distlog --trace

      - name: Create Package Archive
        run: |
          zip -r RomWBW-${{github.ref_name}}-Package.zip . --exclude .git\*

      - name: Set Title
        run: |
          echo "Tag: ${{github.ref_name}}"
          if grep -q "dev" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Development Snapshot"
          elif grep -q "beta" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Beta Release"
          elif grep -q "pre" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Prerelease"
          elif grep -q "rc" <<< "${{github.ref_name}}"; then
            TITLE="RomWBW Release Candidate"
          else
            TITLE="RomWBW"
          fi
          echo "Title: $TITLE"
          echo "TITLE=$TITLE" >>$GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" RomWBW-$TAG-Package.zip \
            --draft --prerelease \
            --title="${{env.TITLE}} $TAG" \
            --generate-notes

      - name: Build Docs
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install gpp pandoc
          pip install mkdocs
          make -C Source/Doc deploy_mkdocs
          mkdocs build -f Source/Doc/mkdocs.yml

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
#       if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Source/Doc/site
